// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ActivityInfernalDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 积分来源
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 时代
        /// </summary>
        public int cityAge = 0 ;

        /// <summary> 
        /// 难度
        /// </summary>
        public int difficulty = 0 ;

        /// <summary> 
        /// 选取几率
        /// </summary>
        public int odds = 0 ;

        /// <summary> 
        /// 优先级
        /// </summary>
        public int order = 0 ;

        /// <summary> 
        /// 阶段1~3所需积分
        /// </summary>
        public List<int> score = null ;

        /// <summary> 
        /// 阶段1~3奖励组
        /// </summary>
        public List<int> reward = null ;

        /// <summary> 
        /// 阶段1~3奖励价值
        /// </summary>
        public List<int> worth = null ;

        /// <summary> 
        /// 排行榜奖励
        /// </summary>
        public int rewardRank = 0 ;

        /// <summary> 
        /// 积分来源描述
        /// </summary>
        public int desID = 0 ;

        /// <summary> 
        /// 积分来源tips
        /// </summary>
        public int tipsID = 0 ;

        /// <summary> 
        /// 积分来源图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 背景颜色色码
        /// </summary>
        public string color = string.Empty ;

    }
}