// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ActivityDropTypeDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 类型
        /// </summary>
        public int activityType = 0 ;

        /// <summary> 
        /// 玩家行为
        /// </summary>
        public int playerBehavior = 0 ;

        /// <summary> 
        /// 参数
        /// </summary>
        public int data0 = 0 ;

        /// <summary> 
        /// 图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 语言包id
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 奖励组
        /// </summary>
        public int itemPackage = 0 ;

        /// <summary> 
        /// 邮件id
        /// </summary>
        public int mailID = 0 ;

        /// <summary> 
        /// 跳转类型
        /// </summary>
        public int jumpType = 0 ;

        /// <summary> 
        /// 是否发奖
        /// </summary>
        public int award = 0 ;

    }
}