// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ActivityKillIntegralDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 类型
        /// </summary>
        public int activityType = 0 ;

        /// <summary> 
        /// 行为组
        /// </summary>
        public int groupsType = 0 ;

        /// <summary> 
        /// 玩家行为
        /// </summary>
        public int playerBehavior = 0 ;

        /// <summary> 
        /// 行为参数{0}
        /// </summary>
        public int data0 = 0 ;

        /// <summary> 
        /// 行为参数{1}
        /// </summary>
        public int data1 = 0 ;

        /// <summary> 
        /// 行为参数{2}
        /// </summary>
        public int data2 = 0 ;

        /// <summary> 
        /// 参数3
        /// </summary>
        public int data3 = 0 ;

        /// <summary> 
        /// 可兑换积分
        /// </summary>
        public int integral = 0 ;

    }
}