// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ActivityConversionTypeDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 类型
        /// </summary>
        public int activityType = 0 ;

        /// <summary> 
        /// vip限制
        /// </summary>
        public int vipLimit = 0 ;

        /// <summary> 
        /// 次数限制
        /// </summary>
        public int timeLimit = 0 ;

        /// <summary> 
        /// 兑换道具
        /// </summary>
        public List<int> conversionItem = null ;

        /// <summary> 
        /// 数量
        /// </summary>
        public List<int> num = null ;

        /// <summary> 
        /// 目标奖励组
        /// </summary>
        public int itemPackage = 0 ;

    }
}