// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ActivityEndHandingDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 类型
        /// </summary>
        public int activityType = 0 ;

        /// <summary> 
        /// 兑换道具
        /// </summary>
        public int conversionItem = 0 ;

        /// <summary> 
        /// 数量
        /// </summary>
        public int conversionNum = 0 ;

        /// <summary> 
        /// 补偿道具
        /// </summary>
        public int itemPackage = 0 ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int mailID = 0 ;

        /// <summary> 
        /// 邮件需求活动id
        /// </summary>
        public int mailActivity = 0 ;

    }
}