// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ActivityNewPlayerDefine
    {
        /// <summary> 
        /// 索引ID（该ID有索引对应奖励，非流水号）
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 
        /// </summary>
        public int actiyityType = 0 ;

        /// <summary> 
        /// 
        /// </summary>
        public int day = 0 ;

        /// <summary> 
        /// 
        /// </summary>
        public int standard = 0 ;

        /// <summary> 
        /// 
        /// </summary>
        public int itemPackage = 0 ;

        /// <summary> 
        /// 
        /// </summary>
        public int mailId = 0 ;

    }
}