// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ActivityKillTypeDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 类型
        /// </summary>
        public int activityType = 0 ;

        /// <summary> 
        /// 市政厅等级
        /// </summary>
        public int lv = 0 ;

        /// <summary> 
        /// 阶段
        /// </summary>
        public int stage = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 持续时间（秒）
        /// </summary>
        public int continueTime = 0 ;

        /// <summary> 
        /// 行为组
        /// </summary>
        public int groupsType = 0 ;

        /// <summary> 
        /// 达标积分
        /// </summary>
        public List<int> standard = null ;

        /// <summary> 
        /// 奖励组
        /// </summary>
        public List<int> itemPackage = null ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 排行榜id
        /// </summary>
        public int leaderboardID = 0 ;

        /// <summary> 
        /// 子排行活动ID
        /// </summary>
        public int subtypeID = 0 ;

        /// <summary> 
        /// 跳转类型
        /// </summary>
        public int jumpType = 0 ;

        /// <summary> 
        /// tips语言包
        /// </summary>
        public int l_tipsID = 0 ;

    }
}