// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ActivityRankingTypeDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 活动类型
        /// </summary>
        public int activityType = 0 ;

        /// <summary> 
        /// 排名区间低
        /// </summary>
        public int targetMin = 0 ;

        /// <summary> 
        /// 排名区间高
        /// </summary>
        public int targetMax = 0 ;

        /// <summary> 
        /// 奖励组
        /// </summary>
        public int itemPackage = 0 ;

        /// <summary> 
        /// 邮件id
        /// </summary>
        public int mailID = 0 ;

    }
}