// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ActivityRewardPreviewDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 开服天数
        /// </summary>
        public int openServiceType = 0 ;

        /// <summary> 
        /// 奖励预览
        /// </summary>
        public int rewardPreview = 0 ;

    }
}