// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ActivityCalendarDefine
    {
        /// <summary> 
        /// 索引ID（该ID有索引对应奖励，非流水号）
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 活动名称颜色
        /// </summary>
        public string nameColour = string.Empty ;

        /// <summary> 
        /// 分页类型
        /// </summary>
        public int page = 0 ;

        /// <summary> 
        /// 活动类型
        /// </summary>
        public int activityType = 0 ;

        /// <summary> 
        /// 时间类型
        /// </summary>
        public int timeType = 0 ;

        /// <summary> 
        /// 服务端时间参数1
        /// </summary>
        public string timeData1 = string.Empty ;

        /// <summary> 
        /// 服务端开始时间
        /// </summary>
        public string startTime = string.Empty ;

        /// <summary> 
        /// 持续时间（秒）
        /// </summary>
        public int durationTime = 0 ;

        /// <summary> 
        /// 是否循环
        /// </summary>
        public int circulation = 0 ;

        /// <summary> 
        /// 第几天循环
        /// </summary>
        public int circulationDay = 0 ;

        /// <summary> 
        /// 最强执政官循环次数
        /// </summary>
        public int circulationTime = 0 ;

        /// <summary> 
        /// 最强执政官前置活动id
        /// </summary>
        public int killPrepositionID = 0 ;

        /// <summary> 
        /// 最强执政官后置活动id
        /// </summary>
        public int killPostpositionID = 0 ;

        /// <summary> 
        /// 开服多少天后停止
        /// </summary>
        public int stopDay = 0 ;

        /// <summary> 
        /// 是否在开服期间隐藏
        /// </summary>
        public int openServiceConceal = 0 ;

        /// <summary> 
        /// 隐藏几天
        /// </summary>
        public int concealDay = 0 ;

        /// <summary> 
        /// 图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_sketchID = 0 ;

        /// <summary> 
        /// 背景底图
        /// </summary>
        public string background = string.Empty ;

        /// <summary> 
        /// 奖励预览
        /// </summary>
        public int itemPackage = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_taglineID = 0 ;

        /// <summary> 
        /// 宣传语色值
        /// </summary>
        public string taglineColour = string.Empty ;

        /// <summary> 
        /// 个人排行榜ID
        /// </summary>
        public int leaderboard = 0 ;

        /// <summary> 
        /// 联盟排行榜ID
        /// </summary>
        public int allianceleaderboard = 0 ;

        /// <summary> 
        /// 排行行为内容
        /// </summary>
        public int leaderboardPlayerBehavior = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_ruleID = 0 ;

        /// <summary> 
        /// 进度条类型
        /// </summary>
        public int progressBar = 0 ;

        /// <summary> 
        /// 是否显示进度条
        /// </summary>
        public int ifShow = 0 ;

        /// <summary> 
        /// 前置活动ID
        /// </summary>
        public int prepositionID = 0 ;

        /// <summary> 
        /// 后置活动ID
        /// </summary>
        public int postpositionID = 0 ;

        /// <summary> 
        /// 活动组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 转盘类型
        /// </summary>
        public string drawType = string.Empty ;

        /// <summary> 
        /// 英雄展示
        /// </summary>
        public string heroShow = string.Empty ;

    }
}