// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ActivityReapTypeDefine
    {
        /// <summary> 
        /// 资源建筑等级
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int lv  { get; set; }

        /// <summary> 
        /// 每次触发的时间（单位：小时）
        /// </summary>
        public float times = 0 ;

        /// <summary> 
        /// 单次操作最多给几次循环
        /// </summary>
        public int timesMax = 0 ;

    }
}