// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ActivityIntegralTypeDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 类型
        /// </summary>
        public int activityType = 0 ;

        /// <summary> 
        /// 市政厅等级
        /// </summary>
        public int lv = 0 ;

        /// <summary> 
        /// 阶段
        /// </summary>
        public int stage = 0 ;

        /// <summary> 
        /// 行为组
        /// </summary>
        public int groupsType = 0 ;

        /// <summary> 
        /// 目标对象
        /// </summary>
        public int target = 0 ;

        /// <summary> 
        /// 达标积分
        /// </summary>
        public int standard = 0 ;

        /// <summary> 
        /// 奖励组
        /// </summary>
        public int itemPackage = 0 ;

        /// <summary> 
        /// 联盟排行类型
        /// </summary>
        public int leaderboardType = 0 ;

        /// <summary> 
        /// 邮件id
        /// </summary>
        public int mailID = 0 ;

        /// <summary> 
        /// 宝箱配置
        /// </summary>
        public string box = string.Empty ;

    }
}