// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class AllianceGiftTypeDefine
    {
        /// <summary> 
        /// 联盟礼包宝箱类型
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 名称
        /// </summary>
        public int l_nameId = 0 ;

        /// <summary> 
        /// 描述文字
        /// </summary>
        public int l_desc = 0 ;

        /// <summary> 
        /// 显示分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 是否根据礼物等级变化
        /// </summary>
        public int levelFlag = 0 ;

        /// <summary> 
        /// 有效时长
        /// </summary>
        public int lastTime = 0 ;

        /// <summary> 
        /// 显示图标
        /// </summary>
        public string iconImg = string.Empty ;

    }
}