// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class AllianceShopItemDefine
    {
        /// <summary> 
        /// 道具ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int itemType  { get; set; }

        /// <summary> 
        /// 显示分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 补货单价
        /// </summary>
        public int stockPrice = 0 ;

        /// <summary> 
        /// 出售单价
        /// </summary>
        public int sellingPrice = 0 ;

    }
}