// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class AllianceSignDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 展示图片资源
        /// </summary>
        public string showIcon = string.Empty ;

        /// <summary> 
        /// 实际使用图标资源
        /// </summary>
        public string realityIcon = string.Empty ;

        /// <summary> 
        /// 颜色
        /// </summary>
        public string colour = string.Empty ;

    }
}