// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class AllianceStudyDefine
    {
        /// <summary> 
        /// ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 描述语言包
        /// </summary>
        public int l_des = 0 ;

        /// <summary> 
        /// 科技大类
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 科技子类型
        /// </summary>
        public int studyType = 0 ;

        /// <summary> 
        /// 科技等级
        /// </summary>
        public int studyLv = 0 ;

        /// <summary> 
        /// 是否为主动技能
        /// </summary>
        public int skillType = 0 ;

        /// <summary> 
        /// 需求前置科技1
        /// </summary>
        public int preconditionStudy1 = 0 ;

        /// <summary> 
        /// 前置科技等级1
        /// </summary>
        public int preconditionLv1 = 0 ;

        /// <summary> 
        /// 需求前置科技2
        /// </summary>
        public int preconditionStudy2 = 0 ;

        /// <summary> 
        /// 前置科技等级2
        /// </summary>
        public int preconditionLv2 = 0 ;

        /// <summary> 
        /// 需求前置科技3
        /// </summary>
        public int preconditionStudy3 = 0 ;

        /// <summary> 
        /// 前置科技等级3
        /// </summary>
        public int preconditionLv3 = 0 ;

        /// <summary> 
        /// 需求前置科技4
        /// </summary>
        public int preconditionStudy4 = 0 ;

        /// <summary> 
        /// 前置科技等级4
        /// </summary>
        public int preconditionLv4 = 0 ;

        /// <summary> 
        /// 需求联盟粮食
        /// </summary>
        public int needFood = 0 ;

        /// <summary> 
        /// 需求联盟木材
        /// </summary>
        public int needWood = 0 ;

        /// <summary> 
        /// 需求联盟石料
        /// </summary>
        public int needStone = 0 ;

        /// <summary> 
        /// 需求联盟金币
        /// </summary>
        public int needGold = 0 ;

        /// <summary> 
        /// 需求联盟积分
        /// </summary>
        public int needLeaguePoints = 0 ;

        /// <summary> 
        /// 属性类型
        /// </summary>
        public int attrType = 0 ;

        /// <summary> 
        /// 提升类型
        /// </summary>
        public List<string> buffType = null ;

        /// <summary> 
        /// 联盟属性提升类型
        /// </summary>
        public List<allianceAttrType> allianceBuffTypeNew = null ;

        /// <summary> 
        /// 玩家属性提升类型
        /// </summary>
        public List<attrType> buffTypeNew = null ;

        /// <summary> 
        /// 联盟领土触发BuffID
        /// </summary>
        public int BuffID = 0 ;

        /// <summary> 
        /// 提升参数
        /// </summary>
        public List<int> buffData = null ;

        /// <summary> 
        /// 研究时间
        /// </summary>
        public int costTime = 0 ;

        /// <summary> 
        /// 科技点总进度
        /// </summary>
        public int progress = 0 ;

        /// <summary> 
        /// 捐献货币类型
        /// </summary>
        public int currencyType = 0 ;

        /// <summary> 
        /// 捐献数量
        /// </summary>
        public int currencyNum = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_buffDesID1 = 0 ;

        /// <summary> 
        /// 简述1语言包
        /// </summary>
        public int l_sketchID1 = 0 ;

        /// <summary> 
        /// 效果描述解析1
        /// </summary>
        public float desData1 = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_buffDesID2 = 0 ;

        /// <summary> 
        /// 简述2语言包
        /// </summary>
        public int l_sketchID2 = 0 ;

        /// <summary> 
        /// 效果描述解析2
        /// </summary>
        public float desData2 = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_fullLevelDes1 = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_fullLevelDes2 = 0 ;

        /// <summary> 
        /// 详细属性界面数据标题文本
        /// </summary>
        public List<int> l_attrTitleID = null ;

        /// <summary> 
        /// 数据模板
        /// </summary>
        public List<int> l_attrTemplate = null ;

        /// <summary> 
        /// 模板解析
        /// </summary>
        public List<float> attrData = null ;

        /// <summary> 
        /// 图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 所在列数
        /// </summary>
        public int columns = 0 ;

        /// <summary> 
        /// 科技所在位置编号
        /// </summary>
        public int location = 0 ;

    }
}