// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class AllianceBuildingTypeDefine
    {
        /// <summary> 
        /// 联盟建筑类型
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int type  { get; set; }

        /// <summary> 
        /// 联盟建筑名称
        /// </summary>
        public int l_nameId = 0 ;

        /// <summary> 
        /// 描述文字1
        /// </summary>
        public int l_desc = 0 ;

        /// <summary> 
        /// 描述文字2
        /// </summary>
        public int l_desc2 = 0 ;

        /// <summary> 
        /// 采集资源类型
        /// </summary>
        public int gatherType = 0 ;

        /// <summary> 
        /// 资源半径
        /// </summary>
        public float radius = 0 ;

        /// <summary> 
        /// 独占区半径
        /// </summary>
        public float radiusCollide = 0 ;

        /// <summary> 
        /// 联盟领地长宽
        /// </summary>
        public int territorySize = 0 ;

        /// <summary> 
        /// 建筑数量上限
        /// </summary>
        public int countDefault = 0 ;

        /// <summary> 
        /// 建造速度参数1
        /// </summary>
        public float X1 = 0 ;

        /// <summary> 
        /// 建造速度参数2
        /// </summary>
        public float Y1 = 0 ;

        /// <summary> 
        /// 建造进度上限
        /// </summary>
        public float S = 0 ;

        /// <summary> 
        /// 存在时间上限
        /// </summary>
        public int timeDefault = 0 ;

        /// <summary> 
        /// 前置建筑类型1
        /// </summary>
        public int preBuilding1 = 0 ;

        /// <summary> 
        /// 前置建筑数量1
        /// </summary>
        public int preNum1 = 0 ;

        /// <summary> 
        /// 需求联盟人数
        /// </summary>
        public int playerNum = 0 ;

        /// <summary> 
        /// 需求联盟总战力
        /// </summary>
        public int alliancePower = 0 ;

        /// <summary> 
        /// 存在时间（秒）
        /// </summary>
        public int stillTime = 0 ;

        /// <summary> 
        /// 部队容量上限
        /// </summary>
        public int armyCntLimit = 0 ;

        /// <summary> 
        /// 队列数量上限
        /// </summary>
        public int queueNum = 0 ;

        /// <summary> 
        /// 耐久度上限
        /// </summary>
        public int durable = 0 ;

        /// <summary> 
        /// 燃烧持续时长（秒）
        /// </summary>
        public int burnLast = 0 ;

        /// <summary> 
        /// 燃烧速度（/小时)
        /// </summary>
        public int durableDown = 0 ;

        /// <summary> 
        /// 灭火CD时间(秒）
        /// </summary>
        public int outFireCD = 0 ;

        /// <summary> 
        /// 维修速度（/小时)
        /// </summary>
        public int durableUp = 0 ;

        /// <summary> 
        /// 维修联盟积分
        /// </summary>
        public int fixFund = 0 ;

        /// <summary> 
        /// 维修代币
        /// </summary>
        public int fixGem = 0 ;

        /// <summary> 
        /// 建设联盟个人积分
        /// </summary>
        public int allianceCoinReward = 0 ;

        /// <summary> 
        /// 联盟资源点产出速度/小时
        /// </summary>
        public int holdAllianceSpeed = 0 ;

        /// <summary> 
        /// 资源点产出个人资源速度/小时
        /// </summary>
        public int holdPersonSpeed = 0 ;

        /// <summary> 
        /// 资源中心储量上限
        /// </summary>
        public int resAmount = 0 ;

        /// <summary> 
        /// 资源中心采集速度/小时
        /// </summary>
        public int collectSpeed = 0 ;

        /// <summary> 
        /// 模型索引
        /// </summary>
        public string modelId = string.Empty ;

        /// <summary> 
        /// 在领土界面的列
        /// </summary>
        public int imgShowIndex = 0 ;

        /// <summary> 
        /// 展示预制
        /// </summary>
        public string imgShow = string.Empty ;

        /// <summary> 
        /// 前置科技类型要求
        /// </summary>
        public int scienceReq = 0 ;

        /// <summary> 
        /// 采集邮件
        /// </summary>
        public int mail = 0 ;

        /// <summary> 
        /// 建造成功邮件
        /// </summary>
        public int buildSuccessMail = 0 ;

        /// <summary> 
        /// 建造失败邮件
        /// </summary>
        public int buildFailMail = 0 ;

        /// <summary> 
        /// 拆除建筑邮件
        /// </summary>
        public int buildRemoveMail = 0 ;

        /// <summary> 
        /// 摧毁建筑邮件
        /// </summary>
        public int buildDestoryMail = 0 ;

        /// <summary> 
        /// 被攻击无驻防邮件
        /// </summary>
        public int buildDefenselessMail = 0 ;

        /// <summary> 
        /// 建筑UI图标
        /// </summary>
        public string iconImg = string.Empty ;

        /// <summary> 
        /// 资源图标
        /// </summary>
        public string icon = string.Empty ;

    }
}