// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class AllianceGiftLevelDefine
    {
        /// <summary> 
        /// 联盟礼物等级
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 升级经验
        /// </summary>
        public int exp = 0 ;

        /// <summary> 
        /// 珍藏类型ID
        /// </summary>
        public int treasureId = 0 ;

    }
}