// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class AllianceTreasureDefine
    {
        /// <summary> 
        /// 联盟珍藏ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 名称
        /// </summary>
        public int l_nameId = 0 ;

        /// <summary> 
        /// 需求钥匙点数
        /// </summary>
        public int reqPoints = 0 ;

        /// <summary> 
        /// 奖励组
        /// </summary>
        public int reward = 0 ;

        /// <summary> 
        /// 可领取有效时长（秒）
        /// </summary>
        public int lastTime = 0 ;

        /// <summary> 
        /// 宝藏图片
        /// </summary>
        public string imgShow = string.Empty ;

    }
}