// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class AllianceOfficiallyDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_officiallyID = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 加成语言包
        /// </summary>
        public int l_addDesID = 0 ;

        /// <summary> 
        /// 语言包解析
        /// </summary>
        public List<int> addDesData = null ;

        /// <summary> 
        /// 加成
        /// </summary>
        public List<string> add = null ;

        /// <summary> 
        /// 
        /// </summary>
        public List<attrType> addAtt = null ;

        /// <summary> 
        /// 加成解析
        /// </summary>
        public List<int> addData = null ;

        /// <summary> 
        /// 图标
        /// </summary>
        public string icon = string.Empty ;

    }
}