// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class AllianceMemberDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 名称
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 成员等级
        /// </summary>
        public int lv = 0 ;

        /// <summary> 
        /// 人数限制
        /// </summary>
        public int researchersLimit = 0 ;

        /// <summary> 
        /// 图标
        /// </summary>
        public string icon = string.Empty ;

    }
}