// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class AllianceMemberJurisdictionDefine
    {
        /// <summary> 
        /// 类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_typeID = 0 ;

        /// <summary> 
        /// R1玩家权限
        /// </summary>
        public int R1 = 0 ;

        /// <summary> 
        /// R2玩家权限
        /// </summary>
        public int R2 = 0 ;

        /// <summary> 
        /// R3玩家权限
        /// </summary>
        public int R3 = 0 ;

        /// <summary> 
        /// R4玩家权限
        /// </summary>
        public int R4 = 0 ;

        /// <summary> 
        /// 盟主
        /// </summary>
        public int R5 = 0 ;

    }
}