// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class AllianceBuildingDataDefine
    {
        /// <summary> 
        /// 系统流水
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 联盟建筑类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 第几座建筑
        /// </summary>
        public int orderNum = 0 ;

        /// <summary> 
        /// 联盟粮食
        /// </summary>
        public int food = 0 ;

        /// <summary> 
        /// 联盟木材
        /// </summary>
        public int wood = 0 ;

        /// <summary> 
        /// 联盟石材
        /// </summary>
        public int stone = 0 ;

        /// <summary> 
        /// 联盟金币
        /// </summary>
        public int coin = 0 ;

        /// <summary> 
        /// 联盟积分
        /// </summary>
        public int fund = 0 ;

    }
}