// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class AllianceGiftRewardDefine
    {
        /// <summary> 
        /// 系统流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 礼物宝箱类型
        /// </summary>
        public int giftType = 0 ;

        /// <summary> 
        /// 礼物等级
        /// </summary>
        public int giftLevel = 0 ;

        /// <summary> 
        /// 对应奖励组ID
        /// </summary>
        public int reward = 0 ;

        /// <summary> 
        /// 礼物点数
        /// </summary>
        public int giftPoint = 0 ;

        /// <summary> 
        /// 钥匙点数
        /// </summary>
        public int keyPoint = 0 ;

    }
}