// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class AllianceAttrInfoDefine
    {
        /// <summary> 
        /// 属性关键字
        /// </summary>
        [PrimaryKey] [AutoIncrement] public allianceAttrType ID  { get; set; }

        /// <summary> 
        /// 属性语言包
        /// </summary>
        public int nameID = 0 ;

        /// <summary> 
        /// 属性图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 数值类型
        /// </summary>
        public int valueType = 0 ;

    }
}