// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class AnnouncementDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_titleID = 0 ;

        /// <summary> 
        /// 类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 标记
        /// </summary>
        public int sign = 0 ;

        /// <summary> 
        /// 插图
        /// </summary>
        public string picture = string.Empty ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 显示关联类型
        /// </summary>
        public int showType = 0 ;

        /// <summary> 
        /// 参数1
        /// </summary>
        public int data1 = 0 ;

        /// <summary> 
        /// 参数2
        /// </summary>
        public int data2 = 0 ;

        /// <summary> 
        /// 跳转类型
        /// </summary>
        public int jumpType = 0 ;

        /// <summary> 
        /// 跳转参数1
        /// </summary>
        public int jumpData1 = 0 ;

        /// <summary> 
        /// 参数2
        /// </summary>
        public int jumpData2 = 0 ;

    }
}