// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ArmsSkillDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_skillID = 0 ;

        /// <summary> 
        /// 技能描述，索引helpTips表ID
        /// </summary>
        public int tipsID = 0 ;

        /// <summary> 
        /// 技能图标
        /// </summary>
        public string skillIcon = string.Empty ;

        /// <summary> 
        /// 兵种克制参数
        /// </summary>
        public List<string> restraintCofig = null ;

        /// <summary> 
        /// 兵种克制参数解析
        /// </summary>
        public List<int> restraintData = null ;

    }
}