// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ArmsDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_armsID = 0 ;

        /// <summary> 
        /// 兵种类型
        /// </summary>
        public int armsType = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_typeName = 0 ;

        /// <summary> 
        /// 兵种子类
        /// </summary>
        public int subType = 0 ;

        /// <summary> 
        /// 兵种等级
        /// </summary>
        public int armsLv = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 兵种解锁科技ID
        /// </summary>
        public int studyID = 0 ;

        /// <summary> 
        /// 兵种展示资源
        /// </summary>
        public string armsShow = string.Empty ;

        /// <summary> 
        /// 兵种头像图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 兵种模型
        /// </summary>
        public string armsModel = string.Empty ;

        /// <summary> 
        /// 时代
        /// </summary>
        public int age = 0 ;

        /// <summary> 
        /// 攻击力
        /// </summary>
        public int attack = 0 ;

        /// <summary> 
        /// 防御力
        /// </summary>
        public int defense = 0 ;

        /// <summary> 
        /// 生命值
        /// </summary>
        public int hpMax = 0 ;

        /// <summary> 
        /// 行军速度
        /// </summary>
        public int speed = 0 ;

        /// <summary> 
        /// 语言包ID
        /// </summary>
        public int l_speedDes = 0 ;

        /// <summary> 
        /// 负载
        /// </summary>
        public int capacity = 0 ;

        /// <summary> 
        /// 战力
        /// </summary>
        public int militaryCapability = 0 ;

        /// <summary> 
        /// 兵种技能
        /// </summary>
        public List<int> armsSkill = null ;

        /// <summary> 
        /// 基础招兵粮食消耗
        /// </summary>
        public int needFood = 0 ;

        /// <summary> 
        /// 基础招兵木材消耗
        /// </summary>
        public int needWood = 0 ;

        /// <summary> 
        /// 基础招兵石料消耗
        /// </summary>
        public int needStone = 0 ;

        /// <summary> 
        /// 基础招兵金币消耗
        /// </summary>
        public int needGlod = 0 ;

        /// <summary> 
        /// 基础招兵时间
        /// </summary>
        public int endTime = 0 ;

        /// <summary> 
        /// 基础伤兵粮食消耗
        /// </summary>
        public int woundedFood = 0 ;

        /// <summary> 
        /// 基础伤兵木材消耗
        /// </summary>
        public int woundedWood = 0 ;

        /// <summary> 
        /// 基础伤兵石料消耗
        /// </summary>
        public int woundedStone = 0 ;

        /// <summary> 
        /// 基础伤兵金币消耗
        /// </summary>
        public int woundedGlod = 0 ;

        /// <summary> 
        /// 基础伤兵时间
        /// </summary>
        public int woundedTime = 0 ;

        /// <summary> 
        /// 神秘商人减少CD
        /// </summary>
        public float mysteryStoreCD = 0 ;

    }
}