// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class AudioConfig3dDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 组名称
        /// </summary>
        public string name = string.Empty ;

        /// <summary> 
        /// 
        /// </summary>
        public float dopplerLevel = 0 ;

        /// <summary> 
        /// 最小距离
        /// </summary>
        public float minDistance = 0 ;

        /// <summary> 
        /// 最大距离
        /// </summary>
        public float maxDistance = 0 ;

        /// <summary> 
        /// 
        /// </summary>
        public float spatialBlend = 0 ;

        /// <summary> 
        /// 
        /// </summary>
        public int spread = 0 ;

        /// <summary> 
        /// 镜头高度音量曲线
        /// </summary>
        public string curve = string.Empty ;

    }
}