// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BacksourcingRestrictDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 协议tag
        /// </summary>
        public int agreementTag = 0 ;

        /// <summary> 
        /// 错误码
        /// </summary>
        public int l_descID = 0 ;

    }
}