// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BattleLossDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 进攻方重伤比例
        /// </summary>
        public int seriousInjuryProportion = 0 ;

        /// <summary> 
        /// 进攻方死亡比例
        /// </summary>
        public int deathProportion = 0 ;

        /// <summary> 
        /// 防守方重伤比例
        /// </summary>
        public int seriousInjuryProportionDefence = 0 ;

        /// <summary> 
        /// 防守方死亡比例
        /// </summary>
        public int deathProportionDefence = 0 ;

        /// <summary> 
        /// 城市援军重伤比例
        /// </summary>
        public int cityReinforceSeriousInjuryProportion = 0 ;

        /// <summary> 
        /// 城市援军死亡比例
        /// </summary>
        public int cityReinforceDeathProportion = 0 ;

    }
}