// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BattleMailRoundDateDefine
    {
        /// <summary> 
        /// 回合
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 间隔回合
        /// </summary>
        public int intervalRound = 0 ;

    }
}