// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BattleMailDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 战斗胜利：单人->单目标
        /// </summary>
        public int victoryMailID1 = 0 ;

        /// <summary> 
        /// 战斗胜利：单人->多目标
        /// </summary>
        public int victoryMailID2 = 0 ;

        /// <summary> 
        /// 战斗胜利：集结队长->单目标
        /// </summary>
        public int victoryMailID3 = 0 ;

        /// <summary> 
        /// 战斗胜利：集结队长->多目标
        /// </summary>
        public int victoryMailID4 = 0 ;

        /// <summary> 
        /// 战斗胜利：集结队员->单目标
        /// </summary>
        public int victoryMailID5 = 0 ;

        /// <summary> 
        /// 战斗胜利：集结队员->多目标
        /// </summary>
        public int victoryMailID6 = 0 ;

        /// <summary> 
        /// 战斗胜利：防守队长->单目标
        /// </summary>
        public int victoryMailID7 = 0 ;

        /// <summary> 
        /// 战斗胜利：防守队长->多目标
        /// </summary>
        public int victoryMailID8 = 0 ;

        /// <summary> 
        /// 战斗胜利：防守队员->单目标
        /// </summary>
        public int victoryMailID9 = 0 ;

        /// <summary> 
        /// 战斗胜利：防守队员->多目标
        /// </summary>
        public int victoryMailID10 = 0 ;

        /// <summary> 
        /// 战斗失败：单人->单目标
        /// </summary>
        public int failMailID1 = 0 ;

        /// <summary> 
        /// 战斗失败：单人->多目标
        /// </summary>
        public int failMailID2 = 0 ;

        /// <summary> 
        /// 战斗失败：队长->单目标
        /// </summary>
        public int failMailID3 = 0 ;

        /// <summary> 
        /// 战斗失败：队长->多目标
        /// </summary>
        public int failMailID4 = 0 ;

        /// <summary> 
        /// 战斗失败：队员->单目标
        /// </summary>
        public int failMailID5 = 0 ;

        /// <summary> 
        /// 战斗失败：队员->多目标
        /// </summary>
        public int failMailID6 = 0 ;

        /// <summary> 
        /// 战斗失败：防守队长->单目标
        /// </summary>
        public int failMailID7 = 0 ;

        /// <summary> 
        /// 战斗失败：防守队长->多目标
        /// </summary>
        public int failMailID8 = 0 ;

        /// <summary> 
        /// 战斗失败：防守队员->单目标
        /// </summary>
        public int failMailID9 = 0 ;

        /// <summary> 
        /// 战斗失败：防守队员->多目标
        /// </summary>
        public int failMailID10 = 0 ;

        /// <summary> 
        /// 战斗无结果：单人->单目标
        /// </summary>
        public int noResultMailID1 = 0 ;

        /// <summary> 
        /// 战斗无结果：单人->多目标
        /// </summary>
        public int noResultMailID2 = 0 ;

        /// <summary> 
        /// 战斗无结果：队长->单目标
        /// </summary>
        public int noResultMailID3 = 0 ;

        /// <summary> 
        /// 战斗无结果：队长->多目标
        /// </summary>
        public int noResultMailID4 = 0 ;

        /// <summary> 
        /// 战斗无结果：队员->单目标
        /// </summary>
        public int noResultMailID5 = 0 ;

        /// <summary> 
        /// 战斗无结果：队员->多目标
        /// </summary>
        public int noResultMailID6 = 0 ;

        /// <summary> 
        /// 战斗无结果：防守队长->单目标
        /// </summary>
        public int noResultMailID7 = 0 ;

        /// <summary> 
        /// 战斗无结果：防守队长->多目标
        /// </summary>
        public int noResultMailID8 = 0 ;

        /// <summary> 
        /// 战斗无结果：防守队员->单目标
        /// </summary>
        public int noResultMailID9 = 0 ;

        /// <summary> 
        /// 战斗无结果：防守队员->多目标
        /// </summary>
        public int noResultMailID10 = 0 ;

    }
}