// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BattleBuffDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 市政厅等级下限
        /// </summary>
        public int minLevel = 0 ;

        /// <summary> 
        /// 市政厅等级上限
        /// </summary>
        public int maxLevel = 0 ;

        /// <summary> 
        /// buff的ID
        /// </summary>
        public int buff = 0 ;

    }
}