// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingHospitalDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 医院等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 医院容量
        /// </summary>
        public int armyCnt = 0 ;

        /// <summary> 
        /// 部队生命值提升（千分比）
        /// </summary>
        public int allHpBuff = 0 ;

        /// <summary> 
        /// 步兵生命值百分比（千分比）
        /// </summary>
        public int infantryHpMaxMulti = 0 ;

        /// <summary> 
        /// 骑兵生命值百分比（千分比）
        /// </summary>
        public int cavalryHpMaxMulti = 0 ;

        /// <summary> 
        /// 弓兵生命值百分比（千分比）
        /// </summary>
        public int bowmenHpMaxMulti = 0 ;

        /// <summary> 
        /// 攻城器械生命值百分比（千分比）
        /// </summary>
        public int siegeCarHpMaxMulti = 0 ;

    }
}