// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingBarracksDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 兵营等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 步兵训练容量
        /// </summary>
        public int infantryTrainNumber = 0 ;

        /// <summary> 
        /// 步兵攻击力百分比(千分比）
        /// </summary>
        public int infantryAttackMulti = 0 ;

        /// <summary> 
        /// 骑兵攻击力百分比(千分比）
        /// </summary>
        public int cavalryAttackMulti = 0 ;

        /// <summary> 
        /// 弓兵攻击力百分比(千分比）
        /// </summary>
        public int bowmenAttackMulti = 0 ;

        /// <summary> 
        /// 攻城器械攻击力百分比(千分比）
        /// </summary>
        public int siegeCarAttackMulti = 0 ;

    }
}