// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingFreightDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 商栈等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 运输容量
        /// </summary>
        public int capacity = 0 ;

        /// <summary> 
        /// 税率（千分比）
        /// </summary>
        public int tax = 0 ;

        /// <summary> 
        /// 运输部队行军速度百分比（千分比）
        /// </summary>
        public int transportSpeedMulti = 0 ;

    }
}