// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingResourcesProduceDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 建筑类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 建筑等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 每小时资源产量
        /// </summary>
        public int produceSpeed = 0 ;

        /// <summary> 
        /// 最小收集显示量
        /// </summary>
        public int gatherMin = 0 ;

        /// <summary> 
        /// 最大可收集量
        /// </summary>
        public int gatherMax = 0 ;

    }
}