// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingStorageDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 仓库等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 粮食包含量
        /// </summary>
        public int foodCnt = 0 ;

        /// <summary> 
        /// 木材保护量
        /// </summary>
        public int woodCnt = 0 ;

        /// <summary> 
        /// 石料保护量
        /// </summary>
        public int stoneCnt = 0 ;

        /// <summary> 
        /// 金币保护量
        /// </summary>
        public int goldCnt = 0 ;

    }
}