// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingAllianceCenterDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 联盟中心等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 城市援军容量
        /// </summary>
        public int defCapacity = 0 ;

        /// <summary> 
        /// 可被帮助次数
        /// </summary>
        public int helpCnt = 0 ;

    }
}