// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingCityWallDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 城墙等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 耐久上限
        /// </summary>
        public int wallDurableMax = 0 ;

    }
}