// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingTavernDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 酒馆等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 金宝箱CD时间（秒）
        /// </summary>
        public int goldBoxCD = 0 ;

        /// <summary> 
        /// 每日免费白银宝箱数量
        /// </summary>
        public int silverBoxCnt = 0 ;

    }
}