// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingCountLimitDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 市政厅等级
        /// </summary>
        public int townLevel = 0 ;

        /// <summary> 
        /// 建筑类型
        /// </summary>
        public int buildType = 0 ;

        /// <summary> 
        /// 数量上限
        /// </summary>
        public int buildCountLimit = 0 ;

    }
}