// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingTownCenterDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 市政厅等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 对应时代
        /// </summary>
        public int age = 0 ;

        /// <summary> 
        /// 部队容量
        /// </summary>
        public int troopsCapacity = 0 ;

        /// <summary> 
        /// 工人队列数量
        /// </summary>
        public int builDqueue = 0 ;

        /// <summary> 
        /// 可派遣队列数量
        /// </summary>
        public int troopsDispatchNumber = 0 ;

        /// <summary> 
        /// 达成时发送邮件
        /// </summary>
        public int mail = 0 ;

    }
}