// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingMenuDataDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 菜单行为
        /// </summary>
        public string func = string.Empty ;

        /// <summary> 
        /// 菜单参数
        /// </summary>
        public int param = 0 ;

        /// <summary> 
        /// 菜单参数1
        /// </summary>
        public int param1 = 0 ;

        /// <summary> 
        /// 非升级/研究/治疗/训练时是否显示
        /// </summary>
        public int showType1 = 0 ;

        /// <summary> 
        /// 升级时是否显示
        /// </summary>
        public int showType2 = 0 ;

        /// <summary> 
        /// 研究/治疗/训练时是否显示
        /// </summary>
        public int showType3 = 0 ;

        /// <summary> 
        /// 最低显示等级
        /// </summary>
        public int showLevelMin = 0 ;

        /// <summary> 
        /// 最高显示等级
        /// </summary>
        public int showLevelMax = 0 ;

        /// <summary> 
        /// 菜单按钮图标
        /// </summary>
        public string btnIcon = string.Empty ;

    }
}