// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingTypeConfigDefine
    {
        /// <summary> 
        /// 建筑类型
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int type  { get; set; }

        /// <summary> 
        /// 名称
        /// </summary>
        public int l_nameId = 0 ;

        /// <summary> 
        /// 建筑分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 是否可移动
        /// </summary>
        public int isMove = 0 ;

        /// <summary> 
        /// 列表TIPS编号
        /// </summary>
        public int tipList = 0 ;

        /// <summary> 
        /// 建筑描述
        /// </summary>
        public int l_descId = 0 ;

        /// <summary> 
        /// 建筑简述
        /// </summary>
        public int l_descId2 = 0 ;

        /// <summary> 
        /// 菜单按钮列表
        /// </summary>
        public List<int> menuButtons = null ;

        /// <summary> 
        /// 长度
        /// </summary>
        public int width = 0 ;

        /// <summary> 
        /// 宽度
        /// </summary>
        public int length = 0 ;

    }
}