// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingCastleDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 军事城堡等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 部队集结容量
        /// </summary>
        public int massTroopsCapacity = 0 ;

    }
}