// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingScoutcampDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 斥候营地等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 斥候行军速度提升(千分比）
        /// </summary>
        public int scoutSpeedMulti = 0 ;

        /// <summary> 
        /// 斥候数量
        /// </summary>
        public int scoutNumber = 0 ;

        /// <summary> 
        /// 探索范围
        /// </summary>
        public int scoutView = 0 ;

        /// <summary> 
        /// 侦察资源类型1
        /// </summary>
        public int costCurrencyType1 = 0 ;

        /// <summary> 
        /// 消耗数量1
        /// </summary>
        public int number1 = 0 ;

        /// <summary> 
        /// 侦察资源类型2
        /// </summary>
        public int costCurrencyType2 = 0 ;

        /// <summary> 
        /// 消耗数量2
        /// </summary>
        public int number2 = 0 ;

    }
}