// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingLevelDataDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 建筑类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 建筑等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 建筑宽度
        /// </summary>
        public int width = 0 ;

        /// <summary> 
        /// 建筑长度
        /// </summary>
        public int length = 0 ;

        /// <summary> 
        /// 前置建筑类型1
        /// </summary>
        public int reqType1 = 0 ;

        /// <summary> 
        /// 前置建筑等级1
        /// </summary>
        public int reqLevel1 = 0 ;

        /// <summary> 
        /// 前置建筑类型2
        /// </summary>
        public int reqType2 = 0 ;

        /// <summary> 
        /// 前置建筑等级2
        /// </summary>
        public int reqLevel2 = 0 ;

        /// <summary> 
        /// 前置建筑类型3
        /// </summary>
        public int reqType3 = 0 ;

        /// <summary> 
        /// 前置建筑等级3
        /// </summary>
        public int reqLevel3 = 0 ;

        /// <summary> 
        /// 粮食需求
        /// </summary>
        public int food = 0 ;

        /// <summary> 
        /// 木材需求
        /// </summary>
        public int wood = 0 ;

        /// <summary> 
        /// 矿石需求
        /// </summary>
        public int stone = 0 ;

        /// <summary> 
        /// 金币需求
        /// </summary>
        public int coin = 0 ;

        /// <summary> 
        /// 代币需求
        /// </summary>
        public int denar = 0 ;

        /// <summary> 
        /// 道具需求类型
        /// </summary>
        public int itemType1 = 0 ;

        /// <summary> 
        /// 道具需求数量
        /// </summary>
        public int itemCnt = 0 ;

        /// <summary> 
        /// 默认升级时间
        /// </summary>
        public int buildingTime = 0 ;

        /// <summary> 
        /// 提供战力值
        /// </summary>
        public int power = 0 ;

        /// <summary> 
        /// 减少神秘商人CD，单位秒
        /// </summary>
        public int mysteryStoreCD = 0 ;

    }
}