// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingStableDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 马厩等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 骑兵训练容量
        /// </summary>
        public int cavalryTrainNumber = 0 ;

        /// <summary> 
        /// 步兵防御力百分比（千分比）
        /// </summary>
        public int infantryDefenseMulti = 0 ;

        /// <summary> 
        /// 骑兵防御力百分比（千分比）
        /// </summary>
        public int cavalryDefenseMulti = 0 ;

        /// <summary> 
        /// 弓兵防御力百分比（千分比）
        /// </summary>
        public int bowmenDefenseMulti = 0 ;

        /// <summary> 
        /// 攻城器械防御力百分比（千分比）
        /// </summary>
        public int siegeCarDefenseMulti = 0 ;

    }
}