// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingMailDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 建筑类型
        /// </summary>
        public int buildingType = 0 ;

        /// <summary> 
        /// 建筑等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 发送邮件ID
        /// </summary>
        public int mailID = 0 ;

    }
}