// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingModelDataDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 建筑类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 文明类型
        /// </summary>
        public int civType = 0 ;

        /// <summary> 
        /// 文明阶段
        /// </summary>
        public int age = 0 ;

        /// <summary> 
        /// 模型资源
        /// </summary>
        public string modelId = string.Empty ;

        /// <summary> 
        /// 图片预制
        /// </summary>
        public string imgRes = string.Empty ;

    }
}