// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class BuildingGuardTowerDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 警戒塔等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 攻击力
        /// </summary>
        public int warningTowerAttack = 0 ;

        /// <summary> 
        /// 生命值
        /// </summary>
        public int warningTowerHpMax = 0 ;

        /// <summary> 
        /// 兵种属性索引
        /// </summary>
        public int armsID = 0 ;

        /// <summary> 
        /// 警戒塔攻城头像
        /// </summary>
        public string towerHead = string.Empty ;

    }
}