// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class CameraParamLodDefine
    {
        /// <summary> 
        /// 设置名称
        /// </summary>
        [PrimaryKey] [AutoIncrement] public string ID  { get; set; }

        /// <summary> 
        /// 镜头高度
        /// </summary>
        public float dist = 0 ;

        /// <summary> 
        /// 镜头广角
        /// </summary>
        public float fov = 0 ;

        /// <summary> 
        /// 镜头面积
        /// </summary>
        public float dxf = 0 ;

        /// <summary> 
        /// 角度参数
        /// </summary>
        public float forwardX = 0 ;

        /// <summary> 
        /// 角度参数
        /// </summary>
        public float forwardY = 0 ;

        /// <summary> 
        /// 角度参数
        /// </summary>
        public float forwardZ = 0 ;

    }
}