// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ChatBlockDefine
    {
        /// <summary> 
        /// 关键字
        /// </summary>
        public string ID = string.Empty ;

    }
}