// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ChatShareDefine
    {
        /// <summary> 
        /// 类型
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 标题语言包
        /// </summary>
        public int l_titleID = 0 ;

        /// <summary> 
        /// 描述语言包
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 主界面聊天框显示语言包
        /// </summary>
        public int chatShow = 0 ;

        /// <summary> 
        /// 分享类型图标
        /// </summary>
        public string iconID = string.Empty ;

        /// <summary> 
        /// 标题颜色
        /// </summary>
        public string color = string.Empty ;

        /// <summary> 
        /// 可分享频道
        /// </summary>
        public List<int> chatChannel = null ;

    }
}