// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ChatEmojiDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 表情分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 表情名称
        /// </summary>
        public int l_nameId = 0 ;

        /// <summary> 
        /// 表情资源索引
        /// </summary>
        public string imgPath = string.Empty ;

        /// <summary> 
        /// 表情预制
        /// </summary>
        public string spine = string.Empty ;

    }
}