// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ChatChannelDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 存储条数
        /// </summary>
        public int saveNum = 0 ;

        /// <summary> 
        /// 落地存储条数
        /// </summary>
        public int saveStorageNum = 0 ;

        /// <summary> 
        /// 发言时间间隔,单位秒
        /// </summary>
        public int timeInterval = 0 ;

        /// <summary> 
        /// 等级限制
        /// </summary>
        public int lvLimit = 0 ;

        /// <summary> 
        /// 频道图标
        /// </summary>
        public string icon = string.Empty ;

    }
}