// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class CityHideDataDefine
    {
        /// <summary> 
        /// 等级段
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 离线回收时间（小时）
        /// </summary>
        public int hideCityTime = 0 ;

    }
}