// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class CityAgeSizeDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 所属时代
        /// </summary>
        public int age = 0 ;

        /// <summary> 
        /// 时代名称
        /// </summary>
        public int l_nameId = 0 ;

        /// <summary> 
        /// 市政厅等级
        /// </summary>
        public int townLevel = 0 ;

        /// <summary> 
        /// 内城尺寸
        /// </summary>
        public int size = 0 ;

        /// <summary> 
        /// 城墙尺寸
        /// </summary>
        public int wallSize = 0 ;

        /// <summary> 
        /// 网格文件
        /// </summary>
        public string mapMesh = string.Empty ;

        /// <summary> 
        /// 时代展现UI
        /// </summary>
        public string ageShowUI = string.Empty ;

        /// <summary> 
        /// 工人数量(男)
        /// </summary>
        public int BuilderMaleNum = 0 ;

        /// <summary> 
        /// 工人数量(女)
        /// </summary>
        public int BuilderFemaleNum = 0 ;

        /// <summary> 
        /// 工人等级
        /// </summary>
        public int BuilderLevel = 0 ;

        /// <summary> 
        /// 开始时代变化前对白ID
        /// </summary>
        public int ageDialogBegin = 0 ;

        /// <summary> 
        /// 结束时代变化时对白ID
        /// </summary>
        public int ageDialogEnd = 0 ;

        /// <summary> 
        /// 警戒塔邮件图标
        /// </summary>
        public string towerMail = string.Empty ;

        /// <summary> 
        /// 警戒塔攻城头像
        /// </summary>
        public string towerHead = string.Empty ;

    }
}