// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class CityBuffGroupDefine
    {
        /// <summary> 
        /// 分组ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 名称语言包
        /// </summary>
        public int nameID = 0 ;

        /// <summary> 
        /// 描述语言包
        /// </summary>
        public int desID = 0 ;

        /// <summary> 
        /// 图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 进度条信息
        /// </summary>
        public int tag = 0 ;

        /// <summary> 
        /// 系列
        /// </summary>
        public int series = 0 ;

        /// <summary> 
        /// 功能
        /// </summary>
        public int func = 0 ;

        /// <summary> 
        /// 叠加规则
        /// </summary>
        public int overlay = 0 ;

    }
}