// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class CityBuffDefine
    {
        /// <summary> 
        /// BuffID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 功能类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 持续时间
        /// </summary>
        public int duration = 0 ;

        /// <summary> 
        /// 属性类型
        /// </summary>
        public List<string> attr = null ;

        /// <summary> 
        /// 属性类型
        /// </summary>
        public List<attrType> attrNew = null ;

        /// <summary> 
        /// 属性值
        /// </summary>
        public List<int> attrData = null ;

        /// <summary> 
        /// 图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 特效
        /// </summary>
        public string effect = string.Empty ;

        /// <summary> 
        /// 进度条信息
        /// </summary>
        public int tag = 0 ;

        /// <summary> 
        /// tip中显示的名字
        /// </summary>
        public int tipName = 0 ;

        /// <summary> 
        /// 进度条数值
        /// </summary>
        public List<int> tagData = null ;

        /// <summary> 
        /// 物品ID
        /// </summary>
        public int item = 0 ;

        /// <summary> 
        /// tag图标
        /// </summary>
        public string tagIcon = string.Empty ;

    }
}