// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class CityBuffSeriesDefine
    {
        /// <summary> 
        /// 系列ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 名称语言包
        /// </summary>
        public int nameID = 0 ;

        /// <summary> 
        /// 叠加规则
        /// </summary>
        public int overlay = 0 ;

        /// <summary> 
        /// 是否显示系列
        /// </summary>
        public int show = 0 ;

    }
}