// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class CivilizationDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_civilizationID = 0 ;

        /// <summary> 
        /// 文明名称颜色
        /// </summary>
        public string civilizationColour = string.Empty ;

        /// <summary> 
        /// 语言包ID
        /// </summary>
        public int l_addNameID = 0 ;

        /// <summary> 
        /// 加成语言包ID
        /// </summary>
        public int l_addDesID = 0 ;

        /// <summary> 
        /// 加成描述解析
        /// </summary>
        public List<int> addData = null ;

        /// <summary> 
        /// 文明加成
        /// </summary>
        public List<string> civilizationAdd = null ;

        /// <summary> 
        /// 文明加成
        /// </summary>
        public List<attrType> civilizationAddNew = null ;

        /// <summary> 
        /// 加成解析
        /// </summary>
        public List<int> civilizationAddData = null ;

        /// <summary> 
        /// 初始统帅
        /// </summary>
        public int initialHero = 0 ;

        /// <summary> 
        /// 特色兵种
        /// </summary>
        public List<int> featureArms = null ;

        /// <summary> 
        /// 创角界面统帅展示资源
        /// </summary>
        public string heroRes = string.Empty ;

        /// <summary> 
        /// 文明旗帜
        /// </summary>
        public string civilizationFlag = string.Empty ;

        /// <summary> 
        /// 文明标签
        /// </summary>
        public string civilizationMark = string.Empty ;

        /// <summary> 
        /// 标签颜色
        /// </summary>
        public string markColour = string.Empty ;

        /// <summary> 
        /// 缩略图展示
        /// </summary>
        public string cityShow = string.Empty ;

        /// <summary> 
        /// 背景图展示
        /// </summary>
        public string background = string.Empty ;

        /// <summary> 
        /// 特色兵种展示资源
        /// </summary>
        public string featureArmsShow = string.Empty ;

        /// <summary> 
        /// 底纹资源
        /// </summary>
        public string shading = string.Empty ;

        /// <summary> 
        /// 底板颜色
        /// </summary>
        public string floorColour = string.Empty ;

        /// <summary> 
        /// 是否显示
        /// </summary>
        public int ifShow = 0 ;

        /// <summary> 
        /// 是否锁定
        /// </summary>
        public int ifLock = 0 ;

        /// <summary> 
        /// 医院标记显示
        /// </summary>
        public int hospitalMark = 0 ;

        /// <summary> 
        /// 创角界面背景音乐
        /// </summary>
        public string bgm = string.Empty ;

        /// <summary> 
        /// 角色头像
        /// </summary>
        public string playerImg = string.Empty ;

        /// <summary> 
        /// 特色兵种展示名称
        /// </summary>
        public int armsName = 0 ;

        /// <summary> 
        /// 创角界面SD动画左右偏移量（x轴坐标便偏移）
        /// </summary>
        public float aboutOffset = 0 ;

    }
}