// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ConfigDefine
    {
        /// <summary> 
        /// 程序使用
        /// </summary>
        public int id = 0 ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public string serverIP = string.Empty ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public int initialFood = 0 ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public int initialWood = 0 ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public int initialStone = 0 ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public int initialGold = 0 ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public int initialDiamond = 0 ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> initialArmsType = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> initialArmsNum = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public int initialBuff = 0 ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> initialDialogueCivilization = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<string> initialDialogueAudio = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> initialRandomLocation = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> provinceCentreCoordinate1 = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> provinceCentreCoordinate2 = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> provinceCentreCoordinate3 = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> provinceCentreCoordinate4 = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> provinceCentreCoordinate5 = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> provinceCentreCoordinate6 = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> provinceCentreCoordinate7 = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> provinceCentreCoordinate8 = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> provinceCentreCoordinate9 = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> provinceCentreCoordinate10 = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> initialRandomRadius = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public int initialRandomTimes = 0 ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public int provinceFlagCleanTime = 0 ;

        /// <summary> 
        /// 城堡回收
        /// </summary>
        public int hideCityLimitNum = 0 ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> initialItemType = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public List<int> initialItemNum = null ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public string initialAcquiescentName_40 = string.Empty ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public string initialAcquiescentName_10 = string.Empty ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public string initialAcquiescentName_1 = string.Empty ;

        /// <summary> 
        /// 创角登录
        /// </summary>
        public string initialAcquiescentName_37 = string.Empty ;

        /// <summary> 
        /// 维护更新
        /// </summary>
        public int maintainRefreshTime = 0 ;

        /// <summary> 
        /// 地图场景
        /// </summary>
        public int kingdomMapWidth = 0 ;

        /// <summary> 
        /// 地图场景
        /// </summary>
        public int kingdomMapLength = 0 ;

        /// <summary> 
        /// 地图场景
        /// </summary>
        public int kingdomClientDistance = 0 ;

        /// <summary> 
        /// 地图场景
        /// </summary>
        public int kingdomMapTileSize = 0 ;

        /// <summary> 
        /// 兵种训练
        /// </summary>
        public int trainingTerminate = 0 ;

        /// <summary> 
        /// 兵种训练
        /// </summary>
        public int trainingFirstTime = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingNum_1 = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingNum_2 = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingNum_3 = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingNum_4 = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingNum_5 = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingNum_6 = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingNum_7 = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingTimePhase1 = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingTimePhase2 = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingInitialZoom = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingFinishZoom = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public string flyingFoodRes = string.Empty ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public string flyingWoodRes = string.Empty ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public string flyingStoneRes = string.Empty ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public string flyingGlodRes = string.Empty ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public string flyingDenarRes = string.Empty ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public string flyingMedalRes = string.Empty ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingFood_X = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingFood_Y = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingWood_X = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingWood_Y = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingStone_X = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingStone_Y = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingGlod_X = 0 ;

        /// <summary> 
        /// 飘字常量
        /// </summary>
        public int flyingGlod_Y = 0 ;

        /// <summary> 
        /// 统帅
        /// </summary>
        public int rareLanguage = 0 ;

        /// <summary> 
        /// 统帅
        /// </summary>
        public List<int> rareStarItem = null ;

        /// <summary> 
        /// 统帅装备
        /// </summary>
        public List<int> heroEquipType = null ;

        /// <summary> 
        /// 资源结算
        /// </summary>
        public int resStatisticsTime = 0 ;

        /// <summary> 
        /// 资源采集
        /// </summary>
        public int allianceResourceGatherAdd = 0 ;

        /// <summary> 
        /// 资源采集
        /// </summary>
        public int resourceGatherFindRadius = 0 ;

        /// <summary> 
        /// 资源采集
        /// </summary>
        public int resourceGatherRefreshFreq = 0 ;

        /// <summary> 
        /// 资源采集
        /// </summary>
        public int resourceGatherPointLevelMax = 0 ;

        /// <summary> 
        /// 资源采集
        /// </summary>
        public int resourceGatherSearchCd = 0 ;

        /// <summary> 
        /// 资源采集
        /// </summary>
        public float resourceGatherRadius = 0 ;

        /// <summary> 
        /// 资源采集
        /// </summary>
        public int foodRaito = 0 ;

        /// <summary> 
        /// 资源采集
        /// </summary>
        public int woodRaito = 0 ;

        /// <summary> 
        /// 资源采集
        /// </summary>
        public int stoneRaito = 0 ;

        /// <summary> 
        /// 资源采集
        /// </summary>
        public int goldRaito = 0 ;

        /// <summary> 
        /// 资源采集
        /// </summary>
        public int diamonRaito = 0 ;

        /// <summary> 
        /// 新手引导
        /// </summary>
        public int guideHero = 0 ;

        /// <summary> 
        /// 新手引导
        /// </summary>
        public int guideHeroStage = 0 ;

        /// <summary> 
        /// 新手引导
        /// </summary>
        public int guideSwich = 0 ;

        /// <summary> 
        /// 新手引导
        /// </summary>
        public int guideExSwich = 0 ;

        /// <summary> 
        /// 新手引导
        /// </summary>
        public int guideHideMapObject = 0 ;

        /// <summary> 
        /// 新手引导
        /// </summary>
        public int guideHideCityName = 0 ;

        /// <summary> 
        /// 新手引导
        /// </summary>
        public List<int> guideTroopsMove = null ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public int attackConstant = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public int ordinaryAttackConstant = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public int counterAttackConstant = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public int healAttackConstant = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public int attackRange = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public int outOfCombat = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public int reinforceTips = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public int healParameter1 = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public float healParameter2 = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public int shieldParameter1 = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public float shieldParameter2 = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public int troopsParameter1 = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public int troopsParameter2 = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public float troopsParameter3 = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public int troopsParameter4 = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public float troopsParameter5 = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public int troopsParameter6 = 0 ;

        /// <summary> 
        /// 战斗
        /// </summary>
        public int cityReinforceDeathProportion = 0 ;

        /// <summary> 
        /// 科技研究
        /// </summary>
        public int studyTerminate = 0 ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int emailSave = 0 ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int emailResourceSave = 0 ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int mailExploreSave = 0 ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int emailResourceHelpSave = 0 ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int emailMessageSave = 0 ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int emailBeScoutSave = 0 ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int emailOperationTemplate = 0 ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int emailOperationExpirationDate = 0 ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int emailTimeInterval = 0 ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int emailRecentContactsNum = 0 ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int emailTitleLimit = 0 ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int emailContentLimit = 0 ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int maxReinforce = 0 ;

        /// <summary> 
        /// 怪物-野蛮人
        /// </summary>
        public int barbarianFreq = 0 ;

        /// <summary> 
        /// 怪物-野蛮人
        /// </summary>
        public int barbarianNum = 0 ;

        /// <summary> 
        /// 怪物-野蛮人
        /// </summary>
        public int monsterSearchCd = 0 ;

        /// <summary> 
        /// 怪物-野蛮人
        /// </summary>
        public int barbarianLevelLimit = 0 ;

        /// <summary> 
        /// 任务章节
        /// </summary>
        public int preChapter = 0 ;

        /// <summary> 
        /// 工人队列
        /// </summary>
        public int workQueueItem = 0 ;

        /// <summary> 
        /// 工人队列
        /// </summary>
        public int workQueueDenar = 0 ;

        /// <summary> 
        /// 工人队列
        /// </summary>
        public int workQueueTime = 0 ;

        /// <summary> 
        /// 工人队列
        /// </summary>
        public int workQueueMax = 0 ;

        /// <summary> 
        /// 军队
        /// </summary>
        public int ArmsDefeatedSpeed = 0 ;

        /// <summary> 
        /// 怪物-野蛮人
        /// </summary>
        public float barbarianRadius = 0 ;

        /// <summary> 
        /// 行动力
        /// </summary>
        public List<int> denarChangeEnery1 = null ;

        /// <summary> 
        /// 行动力
        /// </summary>
        public int denarChangeEnery2 = 0 ;

        /// <summary> 
        /// 迷雾
        /// </summary>
        public int worldMapCompensate = 0 ;

        /// <summary> 
        /// 斥候
        /// </summary>
        public int scoutSpeed = 0 ;

        /// <summary> 
        /// 斥候
        /// </summary>
        public int marchParameter1 = 0 ;

        /// <summary> 
        /// 斥候
        /// </summary>
        public int marchParameter2 = 0 ;

        /// <summary> 
        /// 斥候
        /// </summary>
        public string toScoutsIcon1 = string.Empty ;

        /// <summary> 
        /// 斥候
        /// </summary>
        public string toScoutsIcon2 = string.Empty ;

        /// <summary> 
        /// 斥候
        /// </summary>
        public string toScoutsIcon3 = string.Empty ;

        /// <summary> 
        /// 斥候
        /// </summary>
        public string toScoutsModel1 = string.Empty ;

        /// <summary> 
        /// 斥候
        /// </summary>
        public string toScoutsModel2 = string.Empty ;

        /// <summary> 
        /// 斥候
        /// </summary>
        public string toScoutsModel3 = string.Empty ;

        /// <summary> 
        /// 斥候
        /// </summary>
        public float scoutsRadiusCollide = 0 ;

        /// <summary> 
        /// 侦察
        /// </summary>
        public int detectedLv = 0 ;

        /// <summary> 
        /// 治疗
        /// </summary>
        public int cureMinTime = 0 ;

        /// <summary> 
        /// 治疗
        /// </summary>
        public List<int> cureTriggerProportion = null ;

        /// <summary> 
        /// 治疗
        /// </summary>
        public int cureFullMailID = 0 ;

        /// <summary> 
        /// 治疗
        /// </summary>
        public int cureOverstepMailID = 0 ;

        /// <summary> 
        /// 帮助
        /// </summary>
        public int helpAddProportion = 0 ;

        /// <summary> 
        /// 帮助
        /// </summary>
        public int helpMinAddTime = 0 ;

        /// <summary> 
        /// 帮助
        /// </summary>
        public int individualPointsLimit = 0 ;

        /// <summary> 
        /// 帮助
        /// </summary>
        public int individualPointsAward = 0 ;

        /// <summary> 
        /// 帮助
        /// </summary>
        public int alliancePointsLimit = 0 ;

        /// <summary> 
        /// 帮助
        /// </summary>
        public int alliancePointsAward = 0 ;

        /// <summary> 
        /// 聊天
        /// </summary>
        public int channelWordLimit = 0 ;

        /// <summary> 
        /// 聊天
        /// </summary>
        public int timeStamp = 0 ;

        /// <summary> 
        /// 聊天
        /// </summary>
        public int channelPageLimit = 0 ;

        /// <summary> 
        /// 场景
        /// </summary>
        public float cityRadius = 0 ;

        /// <summary> 
        /// 酒馆
        /// </summary>
        public int silverBoxCD = 0 ;

        /// <summary> 
        /// 酒馆
        /// </summary>
        public int silverBoxOpenItem = 0 ;

        /// <summary> 
        /// 酒馆
        /// </summary>
        public int silverBoxOpenItemNum = 0 ;

        /// <summary> 
        /// 酒馆
        /// </summary>
        public int goldBoxOpenItem = 0 ;

        /// <summary> 
        /// 酒馆
        /// </summary>
        public int goldBoxOpenItemNum = 0 ;

        /// <summary> 
        /// 酒馆
        /// </summary>
        public int silverBoxItemPackage = 0 ;

        /// <summary> 
        /// 酒馆
        /// </summary>
        public int goldBoxItemPackage = 0 ;

        /// <summary> 
        /// 酒馆-引导
        /// </summary>
        public int goldBoxFirstReward = 0 ;

        /// <summary> 
        /// 酒馆
        /// </summary>
        public List<int> boxRewardType = null ;

        /// <summary> 
        /// 场景-昼夜转化
        /// </summary>
        public int dayNightTime = 0 ;

        /// <summary> 
        /// 场景-昼夜转化
        /// </summary>
        public int dawnDuration = 0 ;

        /// <summary> 
        /// 场景-昼夜转化
        /// </summary>
        public int dawnSwitchDuration = 0 ;

        /// <summary> 
        /// 场景-昼夜转化
        /// </summary>
        public int dayDuration = 0 ;

        /// <summary> 
        /// 场景-昼夜转化
        /// </summary>
        public int daySwitchDuration = 0 ;

        /// <summary> 
        /// 场景-昼夜转化
        /// </summary>
        public int duskDuration = 0 ;

        /// <summary> 
        /// 场景-昼夜转化
        /// </summary>
        public int duskSwitchDuration = 0 ;

        /// <summary> 
        /// 场景-昼夜转化
        /// </summary>
        public int nightDuration = 0 ;

        /// <summary> 
        /// 场景-昼夜转化
        /// </summary>
        public int nightSwitch = 0 ;

        /// <summary> 
        /// 场景-昼夜转化
        /// </summary>
        public int daySwitchGuideA = 0 ;

        /// <summary> 
        /// 场景-昼夜转化
        /// </summary>
        public int nightSwitchGuideB = 0 ;

        /// <summary> 
        /// 场景-昼夜转化
        /// </summary>
        public int duskSwitchGuideC = 0 ;

        /// <summary> 
        /// 场景-昼夜转化
        /// </summary>
        public int normalSwitchGuideD = 0 ;

        /// <summary> 
        /// 场景-村庄山洞
        /// </summary>
        public int caveMailFail = 0 ;

        /// <summary> 
        /// 场景-村庄山洞
        /// </summary>
        public int caveMailFind = 0 ;

        /// <summary> 
        /// 场景-村庄山洞
        /// </summary>
        public int villageMailFind = 0 ;

        /// <summary> 
        /// 基础-行动力
        /// </summary>
        public int vitalityLimit = 0 ;

        /// <summary> 
        /// 基础-行动力
        /// </summary>
        public int vitalityRecoveryTime = 0 ;

        /// <summary> 
        /// 基础-改名
        /// </summary>
        public List<int> playerNameLimit = null ;

        /// <summary> 
        /// 基础-改名
        /// </summary>
        public int playerNameCostItem = 0 ;

        /// <summary> 
        /// 基础-改名
        /// </summary>
        public int playerNameCostDenar = 0 ;

        /// <summary> 
        /// 基础-任务
        /// </summary>
        public int initTaskMain = 0 ;

        /// <summary> 
        /// 场景-资源田
        /// </summary>
        public string searchFoodIcon = string.Empty ;

        /// <summary> 
        /// 场景-资源田
        /// </summary>
        public string searchWoodIcon = string.Empty ;

        /// <summary> 
        /// 场景-资源田
        /// </summary>
        public string searchStoneIcon = string.Empty ;

        /// <summary> 
        /// 场景-资源田
        /// </summary>
        public string searchGoldIcon = string.Empty ;

        /// <summary> 
        /// 场景-怪物
        /// </summary>
        public string searchMonsterIcon = string.Empty ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceAbbreviationMin = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceAbbreviationMax = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceFirstAward = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceNameMin = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceNameMax = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceNoticeNum = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceEstablishCost = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceRecommendedTime = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public List<string> allianceRandomManifesto = null ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceInitialNum = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceOfficerCD = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceAbbreviationAmend = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceNameAmend = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int alliancSignAmend = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceApproveNumLimit = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceApproveTimeLimit = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int alliancePowerRefreshTime = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int alliancehelpedTimes = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceRecommendedLimit = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceInviteLimit = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceInactivityDefine = 0 ;

        /// <summary> 
        /// 场景-地图属性
        /// </summary>
        public int mapZoneSFWidth = 0 ;

        /// <summary> 
        /// 基础-行动力
        /// </summary>
        public int vitalityReturnEmail = 0 ;

        /// <summary> 
        /// 建筑-工人
        /// </summary>
        public string builderMaleModel = string.Empty ;

        /// <summary> 
        /// 建筑-工人
        /// </summary>
        public string builderFemaleModel = string.Empty ;

        /// <summary> 
        /// 建筑-巡逻卫兵
        /// </summary>
        public int patrolGuardModel = 0 ;

        /// <summary> 
        /// 场景-村庄
        /// </summary>
        public string villageFlag = string.Empty ;

        /// <summary> 
        /// 场景-山洞
        /// </summary>
        public string canveFlag = string.Empty ;

        /// <summary> 
        /// UI-资源栏
        /// </summary>
        public int foodShowLev = 0 ;

        /// <summary> 
        /// UI-资源栏
        /// </summary>
        public int woodShowLev = 0 ;

        /// <summary> 
        /// UI-资源栏
        /// </summary>
        public int stoneShowLev = 0 ;

        /// <summary> 
        /// UI-资源栏
        /// </summary>
        public int goldShowLev = 0 ;

        /// <summary> 
        /// UI-资源栏
        /// </summary>
        public int denarShowStep = 0 ;

        /// <summary> 
        /// 场景-地图区域
        /// </summary>
        public int kingdonMapZoneRadius = 0 ;

        /// <summary> 
        /// 城墙
        /// </summary>
        public int buildBurnNum = 0 ;

        /// <summary> 
        /// 城墙
        /// </summary>
        public int cityWallBurnTime = 0 ;

        /// <summary> 
        /// 城墙
        /// </summary>
        public int cityWallBurnDurability = 0 ;

        /// <summary> 
        /// 城墙
        /// </summary>
        public int cityWallOutfire = 0 ;

        /// <summary> 
        /// 城墙
        /// </summary>
        public int cityWallMaintainDurability = 0 ;

        /// <summary> 
        /// 城墙
        /// </summary>
        public int cityWallMaintainCoolingTime = 0 ;

        /// <summary> 
        /// 场景
        /// </summary>
        public int mapTargetEffectScale = 0 ;

        /// <summary> 
        /// 斥候-半径
        /// </summary>
        public float scoutRadius = 0 ;

        /// <summary> 
        /// 战斗-PVP
        /// </summary>
        public int activationWarFare = 0 ;

        /// <summary> 
        /// 战斗-PVP
        /// </summary>
        public int attackCityLevel = 0 ;

        /// <summary> 
        /// 战斗-集结
        /// </summary>
        public int rallyCityMinLevel = 0 ;

        /// <summary> 
        /// 战斗-集结
        /// </summary>
        public int rallyJoinTips = 0 ;

        /// <summary> 
        /// 战斗-追踪术
        /// </summary>
        public int scoutStudy1 = 0 ;

        /// <summary> 
        /// 战斗-伪装术
        /// </summary>
        public int scoutStudy2 = 0 ;

        /// <summary> 
        /// 建筑队列
        /// </summary>
        public int workQueueReqVip = 0 ;

        /// <summary> 
        /// 联盟
        /// </summary>
        public int allianceCoinRewardDailyLimit = 0 ;

        /// <summary> 
        /// 联盟-仓库
        /// </summary>
        public int allianceFoodLimit = 0 ;

        /// <summary> 
        /// 联盟-仓库
        /// </summary>
        public int allianceWoodLimit = 0 ;

        /// <summary> 
        /// 联盟-仓库
        /// </summary>
        public int allianceStoneLimit = 0 ;

        /// <summary> 
        /// 联盟-仓库
        /// </summary>
        public int allianceGoldLimit = 0 ;

        /// <summary> 
        /// 联盟-仓库
        /// </summary>
        public int allianceConsumeRecordCnt = 0 ;

        /// <summary> 
        /// 联盟-领地
        /// </summary>
        public int territorySizeMin = 0 ;

        /// <summary> 
        /// 联盟-领地
        /// </summary>
        public int territoryBlockMax = 0 ;

        /// <summary> 
        /// 联盟-领地
        /// </summary>
        public int allianceResourcePersonScale = 0 ;

        /// <summary> 
        /// 联盟-领地
        /// </summary>
        public int allianceResourcePersonTime = 0 ;

        /// <summary> 
        /// 联盟-领地
        /// </summary>
        public int allianceResourcePersonRequestLv = 0 ;

        /// <summary> 
        /// 联盟-领地
        /// </summary>
        public int allianceResourcePointReqLevel = 0 ;

        /// <summary> 
        /// 联盟-领地
        /// </summary>
        public int allianceResourceScale = 0 ;

        /// <summary> 
        /// 基础
        /// </summary>
        public int systemDayTime = 0 ;

        /// <summary> 
        /// 场景-迁城
        /// </summary>
        public float cityRadiusCollide = 0 ;

        /// <summary> 
        /// 场景-迁城
        /// </summary>
        public float resourceGatherRadiusCollide = 0 ;

        /// <summary> 
        /// 场景-迁城
        /// </summary>
        public List<int> provinceOuterRingIds = null ;

        /// <summary> 
        /// 场景-迁城
        /// </summary>
        public int cityRemoveItem1 = 0 ;

        /// <summary> 
        /// 场景-迁城
        /// </summary>
        public int cityRemoveItem2 = 0 ;

        /// <summary> 
        /// 场景-迁城
        /// </summary>
        public int cityRemoveItem3 = 0 ;

        /// <summary> 
        /// 场景-迁城
        /// </summary>
        public int cityRemoveItem4 = 0 ;

        /// <summary> 
        /// 场景-迁城
        /// </summary>
        public float buildingRemoveModelScale = 0 ;

        /// <summary> 
        /// 神秘商人
        /// </summary>
        public int mysteryStoreExist = 0 ;

        /// <summary> 
        /// 神秘商人
        /// </summary>
        public int mysteryStoreCooling = 0 ;

        /// <summary> 
        /// 神秘商人
        /// </summary>
        public int mysteryStoreRefresh = 0 ;

        /// <summary> 
        /// 神秘商人
        /// </summary>
        public List<int> mysteryStoreRefreshPrice = null ;

        /// <summary> 
        /// 充值
        /// </summary>
        public int rechargeDailyGift = 0 ;

        /// <summary> 
        /// 充值
        /// </summary>
        public int rechargeFundVipLimit = 0 ;

        /// <summary> 
        /// 充值
        /// </summary>
        public int rechargeFundPrice = 0 ;

        /// <summary> 
        /// 充值
        /// </summary>
        public int RechargeLimitBagNum = 0 ;

        /// <summary> 
        /// 充值
        /// </summary>
        public int rechargeSaleLimitCD = 0 ;

        /// <summary> 
        /// 运营
        /// </summary>
        public int reviewsCityAge = 0 ;

        /// <summary> 
        /// 铁匠铺
        /// </summary>
        public List<int> equipMaterialMake = null ;

        /// <summary> 
        /// 铁匠铺
        /// </summary>
        public int equipMaterialMakeTime = 0 ;

        /// <summary> 
        /// 铁匠铺
        /// </summary>
        public int equipMaterialMakeNum = 0 ;

        /// <summary> 
        /// 怪物-野蛮人城寨
        /// </summary>
        public int barbarenFestungenFreq = 0 ;

        /// <summary> 
        /// 怪物-野蛮人城寨
        /// </summary>
        public int barbarenFestungenNum1 = 0 ;

        /// <summary> 
        /// 怪物-野蛮人城寨
        /// </summary>
        public int barbarenFestungenNum2 = 0 ;

        /// <summary> 
        /// 怪物-野蛮人城寨
        /// </summary>
        public int barbarenFestungenNum3 = 0 ;

        /// <summary> 
        /// 文明转换
        /// </summary>
        public int civilizationAlterItem = 0 ;

        /// <summary> 
        /// 场景—符文物件
        /// </summary>
        public int collectCircleTime = 0 ;

        /// <summary> 
        /// 联盟—商店
        /// </summary>
        public int allianceShopRecordLimit = 0 ;

        /// <summary> 
        /// 城建-资源运输
        /// </summary>
        public string transportIcon = string.Empty ;

        /// <summary> 
        /// 城建-资源运输
        /// </summary>
        public string transportModel = string.Empty ;

        /// <summary> 
        /// 城建-资源运输
        /// </summary>
        public int transportSpeed = 0 ;

        /// <summary> 
        /// 城建-资源运输
        /// </summary>
        public float transportRadius = 0 ;

        /// <summary> 
        /// 城建-资源运输
        /// </summary>
        public float transportRadiusCollide = 0 ;

        /// <summary> 
        /// 城建-资源运输
        /// </summary>
        public float transportRadiusFind = 0 ;

        /// <summary> 
        /// 城建-资源运输
        /// </summary>
        public int transportSuccessEmail = 0 ;

        /// <summary> 
        /// 城建-资源运输
        /// </summary>
        public int transportFailEmail = 0 ;

        /// <summary> 
        /// Vip商店
        /// </summary>
        public int vipStoreRefresh = 0 ;

        /// <summary> 
        /// 活动
        /// </summary>
        public List<int> activityInfernalTypeNumRate = null ;

        /// <summary> 
        /// 活动
        /// </summary>
        public List<int> activityInfernalDifficultRate = null ;

        /// <summary> 
        /// 活动
        /// </summary>
        public int activityInfernalLevelLimit = 0 ;

        /// <summary> 
        /// 活动
        /// </summary>
        public int activityInfernalMail = 0 ;

        /// <summary> 
        /// 活动
        /// </summary>
        public int activityHarvestLimit = 0 ;

        /// <summary> 
        /// 迷雾探索
        /// </summary>
        public int checkPointMailFind = 0 ;

        /// <summary> 
        /// 迷雾探索
        /// </summary>
        public int holyLandMailFind = 0 ;

        /// <summary> 
        /// 远征-排行榜
        /// </summary>
        public int expeditionRankingInterval = 0 ;

        /// <summary> 
        /// 远征-商店
        /// </summary>
        public List<int> refreshPrice = null ;

        /// <summary> 
        /// 远征-商店
        /// </summary>
        public int heroHead1RefreshDay = 0 ;

        /// <summary> 
        /// 远征-商店
        /// </summary>
        public List<int> heroHead2 = null ;

        /// <summary> 
        /// 远征-商店
        /// </summary>
        public List<int> heroHead3 = null ;

        /// <summary> 
        /// 远征-商店
        /// </summary>
        public int heroHeadTime = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceGemGiftCD = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceDailyUpperLimit = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceWeeklyUpperLimit = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceDailyRankNum = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceWeeklyRankNum = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceGemGiftNum = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceGemGiftIncrease = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceCostGemUpperLimit = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceAcquireSoloFund = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceAcquireStudyDot = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceAcquireFund = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceStudyCrit_1 = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceStudyCrit_2 = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceStudyCrit_5 = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceStudyCrit_10 = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceStudyGiftTime = 0 ;

        /// <summary> 
        /// 联盟-科技
        /// </summary>
        public int AllianceStudyGiftCD = 0 ;

        /// <summary> 
        /// 场景-符文
        /// </summary>
        public string collectFinishEffect = string.Empty ;

        /// <summary> 
        /// 装备
        /// </summary>
        public List<int> equipTalent = null ;

        /// <summary> 
        /// 装备
        /// </summary>
        public float equipTalentPromote = 0 ;

        /// <summary> 
        /// 联盟-留言板
        /// </summary>
        public int allianceMessageNum = 0 ;

        /// <summary> 
        /// 联盟-留言板
        /// </summary>
        public int allianceMessageCharacterLimit = 0 ;

        /// <summary> 
        /// 联盟-留言板
        /// </summary>
        public int allianceMessageTierLimit = 0 ;

        /// <summary> 
        /// 联盟-留言板
        /// </summary>
        public int allianceMessageReplyLimit = 0 ;

        /// <summary> 
        /// 联盟-留言板
        /// </summary>
        public int allianceMessageSyncNum = 0 ;

        /// <summary> 
        /// 联盟-留言板
        /// </summary>
        public int allianceMessageShowReplyNum = 0 ;

        /// <summary> 
        /// 场景-怪物
        /// </summary>
        public List<int> guardianBornTime = null ;

        /// <summary> 
        /// 城建-建筑拆除
        /// </summary>
        public int destoryBuildingScale = 0 ;

        /// <summary> 
        /// 聊天-表情
        /// </summary>
        public int chatEmojiGroupNum = 0 ;

        /// <summary> 
        /// 聊天-表情
        /// </summary>
        public string chatEmojiGroup1 = string.Empty ;

        /// <summary> 
        /// 聊天-表情
        /// </summary>
        public string chatEmojiGroup2 = string.Empty ;

        /// <summary> 
        /// 聊天-表情
        /// </summary>
        public string chatEmojiGroup3 = string.Empty ;

        /// <summary> 
        /// 场景-迁城
        /// </summary>
        public int destoryCityRemoveLevel = 0 ;

        /// <summary> 
        /// 场景-迷雾
        /// </summary>
        public int allDenseFogMileStone = 0 ;

        /// <summary> 
        /// 统帅-天赋
        /// </summary>
        public List<int> heroNameLimit = null ;

        /// <summary> 
        /// 统帅-天赋
        /// </summary>
        public int talentResetItemID = 0 ;

        /// <summary> 
        /// 联盟—建筑
        /// </summary>
        public int allianceFortressMemberNum = 0 ;

        /// <summary> 
        /// 联盟—建筑
        /// </summary>
        public int allianceMemberNumFlag = 0 ;

        /// <summary> 
        /// 聊天-私聊
        /// </summary>
        public int privateChatSaveTime = 0 ;

        /// <summary> 
        /// 军队-创建
        /// </summary>
        public float battleRecommend1 = 0 ;

        /// <summary> 
        /// 军队-创建
        /// </summary>
        public float battleRecommend2 = 0 ;

        /// <summary> 
        /// 军队-创建
        /// </summary>
        public float battleRecommend3 = 0 ;

        /// <summary> 
        /// 军队-创建
        /// </summary>
        public float battleRecommend4 = 0 ;

        /// <summary> 
        /// 联盟-礼物
        /// </summary>
        public int allianceGiftClean = 0 ;

        /// <summary> 
        /// 王国地图
        /// </summary>
        public float kindomMapEffectDelay = 0 ;

        /// <summary> 
        /// 场景-层级
        /// </summary>
        public int previewDataRadius = 0 ;

        /// <summary> 
        /// 跑马灯速度倍率
        /// </summary>
        public float scrollMessageSpeedMul = 0 ;

        /// <summary> 
        /// 邮件-PVE战报
        /// </summary>
        public int monsterSingleBattleInterruptMail = 0 ;

        /// <summary> 
        /// 邮件-PVE战报
        /// </summary>
        public int monsterPluralBattleVectoryMail = 0 ;

        /// <summary> 
        /// 邮件-PVE战报
        /// </summary>
        public int monsterPluralBattleFailMail = 0 ;

        /// <summary> 
        /// 邮件-PVE战报
        /// </summary>
        public int monsterPluralBattleInterruptMail = 0 ;

        /// <summary> 
        /// 采集活动
        /// </summary>
        public int activityDropLimitTimes = 0 ;

        /// <summary> 
        /// 顶部tip表现参数1
        /// </summary>
        public float upTipAnimTimeOn = 0 ;

        /// <summary> 
        /// 顶部tip表现参数2
        /// </summary>
        public float upTipKeepLife = 0 ;

        /// <summary> 
        /// 远征-气泡
        /// </summary>
        public List<int> expeditionVictoryBubble = null ;

        /// <summary> 
        /// 基础-镜头
        /// </summary>
        public int cameraMoveTime = 0 ;

        /// <summary> 
        /// 基础-关卡连接
        /// </summary>
        public int mapConnectHight = 0 ;

        /// <summary> 
        /// 基础-关卡连接
        /// </summary>
        public int mapConnectLength = 0 ;

        /// <summary> 
        /// 迁城-随机迁城
        /// </summary>
        public List<int> randomCityMoveCentre1 = null ;

        /// <summary> 
        /// 迁城-随机迁城
        /// </summary>
        public List<int> randomCityMoveCentre2 = null ;

        /// <summary> 
        /// 迁城-随机迁城
        /// </summary>
        public List<int> randomCityMoveCentre3 = null ;

        /// <summary> 
        /// 迁城-随机迁城
        /// </summary>
        public List<int> randomCityMoveCentre4 = null ;

        /// <summary> 
        /// 迁城-随机迁城
        /// </summary>
        public List<int> randomCityMoveCentre5 = null ;

        /// <summary> 
        /// 迁城-随机迁城
        /// </summary>
        public List<int> randomCityMoveCentre6 = null ;

        /// <summary> 
        /// 迁城-随机迁城
        /// </summary>
        public List<int> randomCityMoveCentre7 = null ;

        /// <summary> 
        /// 迁城-随机迁城
        /// </summary>
        public List<int> randomCityMoveCentre8 = null ;

        /// <summary> 
        /// 迁城-随机迁城
        /// </summary>
        public List<int> randomCityMoveCentre9 = null ;

        /// <summary> 
        /// 迁城-随机迁城
        /// </summary>
        public List<int> randomCityMoveCentre10 = null ;

        /// <summary> 
        /// 迁城-随机迁城
        /// </summary>
        public List<int> randomCityMoveRadius = null ;

        /// <summary> 
        /// 基础—城堡回收
        /// </summary>
        public int hideNewCityFlag = 0 ;

        /// <summary> 
        /// 基础—城堡回收
        /// </summary>
        public int hideCityFreqTime = 0 ;

        /// <summary> 
        /// 军队-创建
        /// </summary>
        public float troopsRadiusMax = 0 ;

        /// <summary> 
        /// 队伍操作—光环时间
        /// </summary>
        public float operatingHaloTime = 0 ;

        /// <summary> 
        /// VIP
        /// </summary>
        public int vipSignDay = 0 ;

        /// <summary> 
        /// 军队-关卡偏移
        /// </summary>
        public float checkPointMoveOffset = 0 ;

        /// <summary> 
        /// 统帅
        /// </summary>
        public int itemGetHide = 0 ;

        /// <summary> 
        /// PVE-行动力减少
        /// </summary>
        public int vitalityReduceUnit = 0 ;

        /// <summary> 
        /// PVE-行动力减少
        /// </summary>
        public int vitalityReduceLevelLimit = 0 ;

        /// <summary> 
        /// 场景-场景标记
        /// </summary>
        public int personMarkerLimit = 0 ;

        /// <summary> 
        /// 场景-场景标记
        /// </summary>
        public int mapMarkerNameLimit = 0 ;

        /// <summary> 
        /// 轻伤兵头像Icon
        /// </summary>
        public List<string> woundedSoldier = null ;

        /// <summary> 
        /// 设置
        /// </summary>
        public int slidingTime = 0 ;

        /// <summary> 
        /// 基础—城堡回收
        /// </summary>
        public int hideCityExitAlliance = 0 ;

        /// <summary> 
        /// 联盟-联盟邀请
        /// </summary>
        public int allianceInviteNumLimit = 0 ;

        /// <summary> 
        /// 引导-任务引导
        /// </summary>
        public int remindActivityTime = 0 ;

        /// <summary> 
        /// 联盟-建造提醒
        /// </summary>
        public int allianceBuildCheckTime = 0 ;

        /// <summary> 
        /// 服务器列表
        /// </summary>
        public int createRoleMax = 0 ;

        /// <summary> 
        /// 服务器列表
        /// </summary>
        public int newseverTimeLimit = 0 ;

        /// <summary> 
        /// 基础—账号
        /// </summary>
        public int accountBindLevel = 0 ;

        /// <summary> 
        /// 场景-刷新检测
        /// </summary>
        public int barbarianFreshTimeGap = 0 ;

        /// <summary> 
        /// 场景-刷新检测
        /// </summary>
        public int barbarianFreshTileGap = 0 ;

        /// <summary> 
        /// 场景-刷新检测
        /// </summary>
        public int resourceFreshTimeGap = 0 ;

        /// <summary> 
        /// 场景-刷新检测
        /// </summary>
        public int resourceFreshTileGap = 0 ;

        /// <summary> 
        /// 场景-刷新检测
        /// </summary>
        public int fortressFreshTimeGap = 0 ;

        /// <summary> 
        /// 场景-刷新检测
        /// </summary>
        public int fortressFreshTileGap = 0 ;

        /// <summary> 
        /// 军队-行军
        /// </summary>
        public int troopMoveAmendRadius = 0 ;

        /// <summary> 
        /// 服务器预警推送
        /// </summary>
        public List<string> serverWarningPush = null ;

        /// <summary> 
        /// 联盟-建造提醒
        /// </summary>
        public int allianceBuildCheckEffectTime = 0 ;

        /// <summary> 
        /// 活动-大转盘
        /// </summary>
        public List<int> turntableDrawParam = null ;

        /// <summary> 
        /// 活动-大转盘
        /// </summary>
        public int turntableLev = 0 ;

        /// <summary> 
        /// 活动-大转盘
        /// </summary>
        public List<int> turntableSafetynum = null ;

        /// <summary> 
        /// 远征头像商店
        /// </summary>
        public List<string> expeditionHeadeffect = null ;

        /// <summary> 
        /// 多部军队-行军
        /// </summary>
        public float moretTroopsClick = 0 ;

        /// <summary> 
        /// 任务-任务显示
        /// </summary>
        public int taskSideShowLimit = 0 ;

        /// <summary> 
        /// 角色战损
        /// </summary>
        public int battleDamComMinLv = 0 ;

        /// <summary> 
        /// 角色战损
        /// </summary>
        public List<int> battleDamComMail = null ;

        /// <summary> 
        /// 角色战损
        /// </summary>
        public int battleDamComCd = 0 ;

        /// <summary> 
        /// 角色战损
        /// </summary>
        public int battleDamMaxNum = 0 ;

        /// <summary> 
        /// 角色战损
        /// </summary>
        public int battleDamHelpTime = 0 ;

        /// <summary> 
        /// 角色战损
        /// </summary>
        public int makeupspeed = 0 ;

    }
}