// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class CurrencyDefine
    {
        /// <summary> 
        /// 货币ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 通货类型
        /// </summary>
        public string name = string.Empty ;

        /// <summary> 
        /// 货币语言包
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 对应item表子分组
        /// </summary>
        public int itemSubType = 0 ;

        /// <summary> 
        /// UI通货图标
        /// </summary>
        public string iconID = string.Empty ;

        /// <summary> 
        /// 货币说明TIPSID
        /// </summary>
        public int tips = 0 ;

    }
}