// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class EffectInfoDefine
    {
        /// <summary> 
        /// 技能ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int skillID  { get; set; }

        /// <summary> 
        /// ID-具体特效的名称，唯一索引
        /// </summary>
        public string effectID = string.Empty ;

        /// <summary> 
        /// 特效结束时间，程序根据此时间移除特效，单位秒99为循环播放不移除
        /// </summary>
        public float endTime = 0 ;

        /// <summary> 
        /// 事件触发条件（配置值/100）秒，用于配置特效扣血时间
        /// </summary>
        public float key = 0 ;

        /// <summary> 
        /// 特效挂载点位置在建筑单位底下增加挂载点以匹配不同的建筑。effect-∞
        /// </summary>
        public string effectLocation = string.Empty ;

        /// <summary> 
        /// 用于挂载不同范围的提示区域combat_1000_1-1507.5combat_1000_2-15011.5combat_1000_3-1807.5combat_1000_4-3609.6combat_1000_5-36011.5
        /// </summary>
        public string effectArea = string.Empty ;

        /// <summary> 
        /// 特效音效
        /// </summary>
        public string sound = string.Empty ;

        /// <summary> 
        /// 是否投掷0自身播放1创建投掷
        /// </summary>
        public int beAttacked = 0 ;

    }
}