// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class EquipComposeDefine
    {
        /// <summary> 
        /// ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 2套装属性
        /// </summary>
        public List<int> compose2 = null ;

        /// <summary> 
        /// 2套装属性参数
        /// </summary>
        public List<int> compose2Add = null ;

        /// <summary> 
        /// 2套装属性参数(千分比，服务端用）
        /// </summary>
        public List<int> compose2AddEx = null ;

        /// <summary> 
        /// 4套装属性
        /// </summary>
        public List<int> compose4 = null ;

        /// <summary> 
        /// 4套装属性参数
        /// </summary>
        public List<int> compose4Add = null ;

        /// <summary> 
        /// 4套装属性参数
        /// </summary>
        public List<int> compose4AddEx = null ;

        /// <summary> 
        /// 6套装属性
        /// </summary>
        public List<int> compose6 = null ;

        /// <summary> 
        /// 6套装属性参数
        /// </summary>
        public List<int> compose6Add = null ;

        /// <summary> 
        /// 6套装属性参数
        /// </summary>
        public List<int> compose6AddEx = null ;

        /// <summary> 
        /// 8套装属性
        /// </summary>
        public List<int> compose8 = null ;

        /// <summary> 
        /// 8套装属性参数
        /// </summary>
        public List<int> compose8Add = null ;

        /// <summary> 
        /// 8套装属性参数
        /// </summary>
        public List<int> compose8AddEx = null ;

    }
}