// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class EquipMaterialDefine
    {
        /// <summary> 
        /// 道具ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int itemID  { get; set; }

        /// <summary> 
        /// 排序
        /// </summary>
        public int order = 0 ;

        /// <summary> 
        /// 组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 品质
        /// </summary>
        public int rare = 0 ;

        /// <summary> 
        /// 各个品质道具参数
        /// </summary>
        public int add = 0 ;

        /// <summary> 
        /// 合成所需个数
        /// </summary>
        public int mixCostNum = 0 ;

        /// <summary> 
        /// 合成后的道具ID
        /// </summary>
        public int mix = 0 ;

        /// <summary> 
        /// 分解后的道具ID
        /// </summary>
        public int split = 0 ;

        /// <summary> 
        /// 分解消耗货币
        /// </summary>
        public int splitCostCur = 0 ;

        /// <summary> 
        /// 分解消耗货币数量
        /// </summary>
        public int splitCostCurNum = 0 ;

        /// <summary> 
        /// 分解获得个数
        /// </summary>
        public int splitGetNum = 0 ;

    }
}