// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class EquipDefine
    {
        /// <summary> 
        /// 道具ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int itemID  { get; set; }

        /// <summary> 
        /// 组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 穿戴等级
        /// </summary>
        public int useLevel = 0 ;

        /// <summary> 
        /// 锻造所需材料
        /// </summary>
        public List<int> makeMaterial = null ;

        /// <summary> 
        /// 锻造所需材料个数
        /// </summary>
        public List<int> makeMaterialNum = null ;

        /// <summary> 
        /// 锻造消耗金币数
        /// </summary>
        public int costGold = 0 ;

        /// <summary> 
        /// 分解获得材料
        /// </summary>
        public List<int> decomposeMaterial = null ;

        /// <summary> 
        /// 分解获得材料个数
        /// </summary>
        public List<int> decomposeMaterialNum = null ;

        /// <summary> 
        /// 装备属性
        /// </summary>
        public List<int> att = null ;

        /// <summary> 
        /// 装备属性参数（服务端，千分比）
        /// </summary>
        public List<int> attAddEx = null ;

        /// <summary> 
        /// 装备属性参数
        /// </summary>
        public List<int> attAdd = null ;

        /// <summary> 
        /// 套装
        /// </summary>
        public int compose = 0 ;

        /// <summary> 
        /// 排序
        /// </summary>
        public int order = 0 ;

    }
}