// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class EquipAttDefine
    {
        /// <summary> 
        /// ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 客户端使用属性
        /// </summary>
        public attrType attNew = attrType.None ;

        /// <summary> 
        /// 属性
        /// </summary>
        public string att = string.Empty ;

        /// <summary> 
        /// 语言包ID
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 颜色
        /// </summary>
        public string color = string.Empty ;

    }
}