// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class EvolutionRankRewardDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 排行类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 最低排名
        /// </summary>
        public int rankMin = 0 ;

        /// <summary> 
        /// 最高排名
        /// </summary>
        public int rankMax = 0 ;

        /// <summary> 
        /// 奖励数据
        /// </summary>
        public int reward = 0 ;

        /// <summary> 
        /// 奖励展示数据
        /// </summary>
        public int rewardShow = 0 ;

    }
}