// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ExpeditionBattleDefine
    {
        /// <summary> 
        /// ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 关卡名称
        /// </summary>
        public int nameID = 0 ;

        /// <summary> 
        /// 地图ID
        /// </summary>
        public string mapID = string.Empty ;

        /// <summary> 
        /// 地图大小
        /// </summary>
        public List<int> mapSize = null ;

        /// <summary> 
        /// 初始镜头坐标点
        /// </summary>
        public List<int> initialCamera = null ;

        /// <summary> 
        /// X坐标偏移量
        /// </summary>
        public int deviationX = 0 ;

        /// <summary> 
        /// Y坐标偏移量
        /// </summary>
        public int deviationY = 0 ;

        /// <summary> 
        /// 城市皮肤
        /// </summary>
        public string playerCitySkin = string.Empty ;

        /// <summary> 
        /// 玩家城市坐标
        /// </summary>
        public List<int> playerCityBornInfo = null ;

        /// <summary> 
        /// 玩家城市兵力上限
        /// </summary>
        public int playerCityMaxNumber = 0 ;

        /// <summary> 
        /// 集结部队出生信息
        /// </summary>
        public List<int> playerRallyBornInfo = null ;

        /// <summary> 
        /// 加入集结部队出生点1
        /// </summary>
        public int joinRallyBornInfo1 = 0 ;

        /// <summary> 
        /// 加入集结部队出生点2
        /// </summary>
        public int joinRallyBornInfo2 = 0 ;

        /// <summary> 
        /// 加入集结部队出生点3
        /// </summary>
        public int joinRallyBornInfo3 = 0 ;

        /// <summary> 
        /// 加入集结部队出生点4
        /// </summary>
        public int joinRallyBornInfo4 = 0 ;

        /// <summary> 
        /// 加入集结部队出生点5
        /// </summary>
        public int joinRallyBornInfo5 = 0 ;

        /// <summary> 
        /// 玩家部队1出生信息
        /// </summary>
        public List<int> playerBornInfo1 = null ;

        /// <summary> 
        /// 玩家部队2出生信息
        /// </summary>
        public List<int> playerBornInfo2 = null ;

        /// <summary> 
        /// 玩家部队3出生信息
        /// </summary>
        public List<int> playerBornInfo3 = null ;

        /// <summary> 
        /// 玩家部队4出生信息
        /// </summary>
        public List<int> playerBornInfo4 = null ;

        /// <summary> 
        /// 玩家部队5出生信息
        /// </summary>
        public List<int> playerBornInfo5 = null ;

        /// <summary> 
        /// BOSS怪ID
        /// </summary>
        public int bossID = 0 ;

        /// <summary> 
        /// boss出生信息
        /// </summary>
        public List<int> bossBornInfo = null ;

        /// <summary> 
        /// 目标城市皮肤
        /// </summary>
        public string targetCitySkin = string.Empty ;

        /// <summary> 
        /// 驻守目标城市怪物ID
        /// </summary>
        public int targetCityMonsterID = 0 ;

        /// <summary> 
        /// 驻守目标城市警戒塔等级
        /// </summary>
        public int targetCityGuardTowerlevel = 0 ;

        /// <summary> 
        /// 目标城市出生点
        /// </summary>
        public List<int> targetCityBornInfo = null ;

        /// <summary> 
        /// 怪物刷新间隔
        /// </summary>
        public List<int> monsterRefreshTimes = null ;

        /// <summary> 
        /// 怪物1ID
        /// </summary>
        public int monster1ID = 0 ;

        /// <summary> 
        /// 怪物1出生信息
        /// </summary>
        public List<int> monster1BornInfo = null ;

        /// <summary> 
        /// 怪物1刷新规则
        /// </summary>
        public List<int> monster1RefreshRule = null ;

        /// <summary> 
        /// 怪物2ID
        /// </summary>
        public int monster2ID = 0 ;

        /// <summary> 
        /// 怪物2出生信息
        /// </summary>
        public List<int> monster2BornInfo = null ;

        /// <summary> 
        /// 怪物2刷新规则
        /// </summary>
        public List<int> monster2RefreshRule = null ;

        /// <summary> 
        /// 怪物3ID
        /// </summary>
        public int monster3ID = 0 ;

        /// <summary> 
        /// 怪物3出生信息
        /// </summary>
        public List<int> monster3BornInfo = null ;

        /// <summary> 
        /// 怪物3刷新规则
        /// </summary>
        public List<int> monster3RefreshRule = null ;

        /// <summary> 
        /// 怪物4ID
        /// </summary>
        public int monster4ID = 0 ;

        /// <summary> 
        /// 怪物4出生信息
        /// </summary>
        public List<int> monster4BornInfo = null ;

        /// <summary> 
        /// 怪物4刷新规则
        /// </summary>
        public List<int> monster4RefreshRule = null ;

        /// <summary> 
        /// 怪物5ID
        /// </summary>
        public int monster5ID = 0 ;

        /// <summary> 
        /// 怪物5出生信息
        /// </summary>
        public List<int> monster5BornInfo = null ;

        /// <summary> 
        /// 怪物5刷新规则
        /// </summary>
        public List<int> monster5RefreshRule = null ;

        /// <summary> 
        /// 范围
        /// </summary>
        public int rangeDistance = 0 ;

    }
}