// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ExpeditionShopDefine
    {
        /// <summary> 
        /// ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 刷新位ID
        /// </summary>
        public int groupID = 0 ;

        /// <summary> 
        /// 道具ID索引
        /// </summary>
        public int itemID = 0 ;

        /// <summary> 
        /// 刷新数量
        /// </summary>
        public int number = 0 ;

        /// <summary> 
        /// 刷新权重
        /// </summary>
        public int weight = 0 ;

        /// <summary> 
        /// 远征币价格
        /// </summary>
        public int price = 0 ;

    }
}