// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ExpeditionDefine
    {
        /// <summary> 
        /// ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 关卡等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 前置关卡数
        /// </summary>
        public int frontNumber = 0 ;

        /// <summary> 
        /// 关卡坐标点
        /// </summary>
        public List<int> battleCoordinate = null ;

        /// <summary> 
        /// 战役类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 战斗ID索引
        /// </summary>
        public int battleID = 0 ;

        /// <summary> 
        /// 挑战时间上限
        /// </summary>
        public int times = 0 ;

        /// <summary> 
        /// 2星条件类型及参数
        /// </summary>
        public List<int> starCondition2 = null ;

        /// <summary> 
        /// 3星条件类型及参数
        /// </summary>
        public List<int> starCondition3 = null ;

        /// <summary> 
        /// 星级描述
        /// </summary>
        public List<int> starDesc = null ;

        /// <summary> 
        /// 可派遣部队数
        /// </summary>
        public int troopsNumber = 0 ;

        /// <summary> 
        /// 首胜奖励组
        /// </summary>
        public int firstReward = 0 ;

        /// <summary> 
        /// 1星奖励组
        /// </summary>
        public int reward1 = 0 ;

        /// <summary> 
        /// 2星奖励组
        /// </summary>
        public int reward2 = 0 ;

        /// <summary> 
        /// 3星奖励组
        /// </summary>
        public int reward3 = 0 ;

    }
}