// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ExpeditionHeadDefine
    {
        /// <summary> 
        /// ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 道具ID
        /// </summary>
        public int itemID = 0 ;

        /// <summary> 
        /// 对应统帅ID
        /// </summary>
        public int heroID = 0 ;

        /// <summary> 
        /// 远征币价格
        /// </summary>
        public int price = 0 ;

    }
}