// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class GameSpriteDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 分组及语言包
        /// </summary>
        public int title = 0 ;

        /// <summary> 
        /// 问题内容
        /// </summary>
        public int subTitle = 0 ;

        /// <summary> 
        /// 问题答案
        /// </summary>
        public int text = 0 ;

    }
}