// Generated by zhengjie
// DO NOT EDIT!!
using System.Collections.Generic;
namespace Data
{
    

    public enum allianceAttrType 
    {
        None = 0 ,     // 
        allianceMemberNum = 1 ,     // allianceMemberNum
        allianceDepotMulti = 2 ,     // allianceDepotMulti
        allianceBuildingCostMulti = 3 ,     // allianceBuildingCostMulti
        allianceFlagNum = 4 ,     // allianceFlagNum
        allianceBuildingDurableMulti = 5 ,     // allianceBuildingDurableMulti
        allianceBuildingSpeedMulti = 6 ,     // allianceBuildingSpeedMulti
        allianceFlagSpeedMulti = 7 ,     // allianceFlagSpeedMulti
    }

    public enum attrType 
    {
        None = 0 ,     // 
        troopsCapacity = 1 ,     // troopsCapacity
        massTroopsCapacity = 2 ,     // massTroopsCapacity
        troopsDispatchNumber = 3 ,     // troopsDispatchNumber
        angerMax = 4 ,     // angerMax
        troopsAnger = 5 ,     // troopsAnger
        attackAnger = 6 ,     // attackAnger
        attackAngerMulti = 7 ,     // attackAngerMulti
        heroExpMulti = 8 ,     // heroExpMulti
        barbarianDamageMulti = 9 ,     // barbarianDamageMulti
        barbarianVillageDamageMulti = 10 ,     // barbarianVillageDamageMulti
        barbarianAttackDamageMulti = 11 ,     // barbarianAttackDamageMulti
        barbarianFightBackDamageMulti = 12 ,     // barbarianFightBackDamageMulti
        barbarianAttackDamageReduceMulti = 13 ,     // barbarianAttackDamageReduceMulti
        barbarianFightBackDamageReduceMulti = 14 ,     // barbarianFightBackDamageReduceMulti
        barbarianVillageAttackDamageMulti = 15 ,     // barbarianVillageAttackDamageMulti
        barbarianVillageFightBackDamageMulti = 16 ,     // barbarianVillageFightBackDamageMulti
        barbarianVillageAttackDamageReduceMulti = 17 ,     // barbarianVillageAttackDamageReduceMulti
        barbarianVillageFightBackDamageReduceMulti = 18 ,     // barbarianVillageFightBackDamageReduceMulti
        barbarianSkillDamageMulti = 19 ,     // barbarianSkillDamageMulti
        barbarianSkillDamageReduceMulti = 20 ,     // barbarianSkillDamageReduceMulti
        barbarianVillageSkillDamageMulti = 21 ,     // barbarianVillageSkillDamageMulti
        barbarianVillageSkillDamageReduceMulti = 22 ,     // barbarianVillageSkillDamageReduceMulti
        infantryVsCavalryDamageMulti = 23 ,     // infantryVsCavalryDamageMulti
        infantryVsSiegeCarDamageMulti = 24 ,     // infantryVsSiegeCarDamageMulti
        infantryVsWarningTowerDamageMulti = 25 ,     // infantryVsWarningTowerDamageMulti
        cavalryVsBowmenDamageMulti = 26 ,     // cavalryVsBowmenDamageMulti
        cavalryVsSiegeCarDamageMulti = 27 ,     // cavalryVsSiegeCarDamageMulti
        cavalryVsWarningTowerDamageMulti = 28 ,     // cavalryVsWarningTowerDamageMulti
        bowmenVsInfantryDamageMulti = 29 ,     // bowmenVsInfantryDamageMulti
        bowmenVsSiegeCarDamageMulti = 30 ,     // bowmenVsSiegeCarDamageMulti
        bowmenVsWarningTowerDamageMulti = 31 ,     // bowmenVsWarningTowerDamageMulti
        siegeCarVsWarningTowerDamageMulti = 32 ,     // siegeCarVsWarningTowerDamageMulti
        infantryVsInfantryReduceMulti = 33 ,     // infantryVsInfantryReduceMulti
        infantryVsCavalryReduceMulti = 34 ,     // infantryVsCavalryReduceMulti
        infantryVsBowmenReduceMulti = 35 ,     // infantryVsBowmenReduceMulti
        infantryVsSiegeCarReduceMulti = 36 ,     // infantryVsSiegeCarReduceMulti
        infantryVsWarningTowerReduceMulti = 37 ,     // infantryVsWarningTowerReduceMulti
        attackDamageMulti = 38 ,     // attackDamageMulti
        fightBackDamageMulti = 39 ,     // fightBackDamageMulti
        skillDamageMulti = 40 ,     // skillDamageMulti
        mainHeroSkillDamageMulti = 41 ,     // mainHeroSkillDamageMulti
        secondaryHeroSkillDamageMulti = 42 ,     // secondaryHeroSkillDamageMulti
        attackDamageReduceMulti = 43 ,     // attackDamageReduceMulti
        fightBackDamageReduceMulti = 44 ,     // fightBackDamageReduceMulti
        skillDamageReduceMulti = 45 ,     // skillDamageReduceMulti
        cityDefenseAttackDamageMulti = 46 ,     // cityDefenseAttackDamageMulti
        cityDefenseFightBackDamageMulti = 47 ,     // cityDefenseFightBackDamageMulti
        cityDefenseSkillDamageMulti = 48 ,     // cityDefenseSkillDamageMulti
        cityDefenseAttackDamageReduceMulti = 49 ,     // cityDefenseAttackDamageReduceMulti
        cityDefenseFightBackDamageReduceMulti = 50 ,     // cityDefenseFightBackDamageReduceMulti
        cityDefenseSkillDamageReduceMulti = 51 ,     // cityDefenseSkillDamageReduceMulti
        cityAttackDamageMulti = 52 ,     // cityAttackDamageMulti
        cityFightBackDamageMulti = 53 ,     // cityFightBackDamageMulti
        citySkillDamageMulti = 54 ,     // citySkillDamageMulti
        cityAttackDamageReduceMulti = 55 ,     // cityAttackDamageReduceMulti
        cityFightBackDamageReduceMulti = 56 ,     // cityFightBackDamageReduceMulti
        citySkillDamageReduceMulti = 57 ,     // citySkillDamageReduceMulti
        massAttackDamageMulti = 58 ,     // massAttackDamageMulti
        massFightBackDamageMulti = 59 ,     // massFightBackDamageMulti
        massSkillDamageMulti = 60 ,     // massSkillDamageMulti
        massAttackDamageReduceMulti = 61 ,     // massAttackDamageReduceMulti
        massFightBackDamageReduceMulti = 62 ,     // massFightBackDamageReduceMulti
        massSkillDamageReduceMulti = 63 ,     // massSkillDamageReduceMulti
        garrisonAttackDamageMulti = 64 ,     // garrisonAttackDamageMulti
        garrisonFightBackDamageMulti = 65 ,     // garrisonFightBackDamageMulti
        garrisonSkillDamageMulti = 66 ,     // garrisonSkillDamageMulti
        wallDurableMax = 67 ,     // wallDurableMax
        infantryTrainNumber = 68 ,     // infantryTrainNumber
        cavalryTrainNumber = 69 ,     // cavalryTrainNumber
        bowmenTrainNumber = 70 ,     // bowmenTrainNumber
        siegeCarTrainNumber = 71 ,     // siegeCarTrainNumber
        infantryAttack = 72 ,     // infantryAttack
        cavalryAttack = 73 ,     // cavalryAttack
        bowmenAttack = 74 ,     // bowmenAttack
        siegeCarAttack = 75 ,     // siegeCarAttack
        warningTowerAttack = 76 ,     // warningTowerAttack
        infantryDefense = 77 ,     // infantryDefense
        cavalryDefense = 78 ,     // cavalryDefense
        bowmenDefense = 79 ,     // bowmenDefense
        siegeCarDefense = 80 ,     // siegeCarDefense
        warningTowerDefense = 81 ,     // warningTowerDefense
        infantryHpMax = 82 ,     // infantryHpMax
        cavalryHpMax = 83 ,     // cavalryHpMax
        bowmenHpMax = 84 ,     // bowmenHpMax
        siegeCarHpMax = 85 ,     // siegeCarHpMax
        warningTowerHpMax = 86 ,     // warningTowerHpMax
        infantryMoveSpeed = 87 ,     // infantryMoveSpeed
        cavalryMoveSpeed = 88 ,     // cavalryMoveSpeed
        bowmenMoveSpeed = 89 ,     // bowmenMoveSpeed
        siegeCarMoveSpeed = 90 ,     // siegeCarMoveSpeed
        guardTowerAttack = 91 ,     // guardTowerAttack
        guardTowerDefense = 92 ,     // guardTowerDefense
        guardTowerHpMax = 93 ,     // guardTowerHpMax
        troopsCapacityMulti = 94 ,     // troopsCapacityMulti
        massTroopsCapacityMulti = 95 ,     // massTroopsCapacityMulti
        lightInjuredMulti = 96 ,     // lightInjuredMulti
        severeInjuredMulti = 97 ,     // severeInjuredMulti
        deathMulti = 98 ,     // deathMulti
        troopsHealthMulti = 99 ,     // troopsHealthMulti
        troopsToHealthMulti = 100 ,     // troopsToHealthMulti
        infantryAttackMulti = 101 ,     // infantryAttackMulti
        cavalryAttackMulti = 102 ,     // cavalryAttackMulti
        bowmenAttackMulti = 103 ,     // bowmenAttackMulti
        siegeCarAttackMulti = 104 ,     // siegeCarAttackMulti
        rallyAttackMulti = 105 ,     // rallyAttackMulti
        garrisonAttackMulti = 106 ,     // garrisonAttackMulti
        infantryDefenseMulti = 107 ,     // infantryDefenseMulti
        cavalryDefenseMulti = 108 ,     // cavalryDefenseMulti
        bowmenDefenseMulti = 109 ,     // bowmenDefenseMulti
        siegeCarDefenseMulti = 110 ,     // siegeCarDefenseMulti
        rallyDefenseMulti = 111 ,     // rallyDefenseMulti
        garrisonDefenseMulti = 112 ,     // garrisonDefenseMulti
        infantryHpMaxMulti = 113 ,     // infantryHpMaxMulti
        cavalryHpMaxMulti = 114 ,     // cavalryHpMaxMulti
        bowmenHpMaxMulti = 115 ,     // bowmenHpMaxMulti
        siegeCarHpMaxMulti = 116 ,     // siegeCarHpMaxMulti
        rallyHpMaxMulti = 117 ,     // rallyHpMaxMulti
        garrisonHpMaxMulti = 118 ,     // garrisonHpMaxMulti
        infantryMoveSpeedMulti = 119 ,     // infantryMoveSpeedMulti
        cavalryMoveSpeedMulti = 120 ,     // cavalryMoveSpeedMulti
        bowmenMoveSpeedMulti = 121 ,     // bowmenMoveSpeedMulti
        siegeCarMoveSpeedMulti = 122 ,     // siegeCarMoveSpeedMulti
        marchSpeedMulti = 123 ,     // marchSpeedMulti
        rallyMoveSpeedMulti = 124 ,     // rallyMoveSpeedMulti
        rallyTimesReduce = 125 ,     // rallyTimesReduce
        troopsHealthResourcesMulti = 126 ,     // troopsHealthResourcesMulti
        guardTowerAttackMulti = 127 ,     // guardTowerAttackMulti
        guardTowerDefenseMulti = 128 ,     // guardTowerDefenseMulti
        guardTowerHpMaxMulti = 129 ,     // guardTowerHpMaxMulti
        attackCityDeathMulti = 130 ,     // attackCityDeathMulti
        scoutSpeedMulti = 131 ,     // scoutSpeedMulti
        scoutNumber = 132 ,     // scoutNumber
        scoutView = 133 ,     // scoutView
        vitalityReduction = 134 ,     // vitalityReduction
        allTerrMoveSpeedMulti = 135 ,     // allTerrMoveSpeedMulti
        allTerrAtkMulti = 136 ,     // allTerrAtkMulti
        allTerrBurnSpeedMulti = 137 ,     // allTerrBurnSpeedMulti
        builDqueue = 138 ,     // builDqueue
        buildSpeedMulti = 139 ,     // buildSpeedMulti
        researchSpeedMulti = 140 ,     // researchSpeedMulti
        trainSpeedMulti = 141 ,     // trainSpeedMulti
        healSpeedMulti = 142 ,     // healSpeedMulti
        foodCapacityMulti = 143 ,     // foodCapacityMulti
        woodCapacityMulti = 144 ,     // woodCapacityMulti
        stoneCapacityMulti = 145 ,     // stoneCapacityMulti
        glodCapacityMulti = 146 ,     // glodCapacityMulti
        getFoodSpeedMulti = 147 ,     // getFoodSpeedMulti
        getWoodSpeedMulti = 148 ,     // getWoodSpeedMulti
        getStoneSpeedMulti = 149 ,     // getStoneSpeedMulti
        getGlodSpeedMulti = 150 ,     // getGlodSpeedMulti
        getDiamondSpeedMulti = 151 ,     // getDiamondSpeedMulti
        troopsSpaceMulti = 152 ,     // troopsSpaceMulti
        extraResourcesMulti = 153 ,     // extraResourcesMulti
        resourcesProtectSpaceMulti = 154 ,     // resourcesProtectSpaceMulti
        maxVitality = 155 ,     // maxVitality
        equipmentProduceSpeedMulti = 156 ,     // equipmentProduceSpeedMulti
        hospitalSpaceMulti = 157 ,     // hospitalSpaceMulti
        vitalityRecoveryMulti = 158 ,     // vitalityRecoveryMulti
        transportSpeedMulti = 159 ,     // transportSpeedMulti
        allianceHelpTime = 160 ,     // allianceHelpTime
    }


    public partial class BASE_LIST
    {
        public static readonly List<int> int_DEF_LIST = new List<int>(0);
        public static readonly List<float> float_DEF_LIST = new List<float>(0);
        public static readonly List<string> string_DEF_LIST = new List<string>(0);
    }

    public partial class DATA_LIST
    {
        public static readonly List<allianceAttrType> allianceAttrType_DEF_LIST = new List<allianceAttrType>(0);
        public static readonly List<attrType> attrType_DEF_LIST = new List<attrType>(0);
        public static readonly getWay getWay_DEFAULT = new getWay();
        public static readonly List<getWay> getWay_DEF_LIST = new List<getWay>(0);
    }

    public partial class getWay 
    {
        /// <summary> 
        /// npc 
        /// </summary>
        public int  npc = 0 ;

        /// <summary> 
        /// script 
        /// </summary>
        public int  script = 0 ;

        /// <summary> 
        /// npc 
        /// </summary>
        public int  ui = 0 ;

        /// <summary> 
        /// script 
        /// </summary>
        public int  parm = 0 ;

    }

}