// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class GuideDialogDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 步骤
        /// </summary>
        public int step = 0 ;

        /// <summary> 
        /// 剧情对白语言包
        /// </summary>
        public int l_dialogText = 0 ;

        /// <summary> 
        /// 对白角色模型
        /// </summary>
        public string model = string.Empty ;

        /// <summary> 
        /// 按文明时代指向的模型索引
        /// </summary>
        public List<string> npcAgeModel = null ;

        /// <summary> 
        /// 对白触发额外条件
        /// </summary>
        public int delay = 0 ;

        /// <summary> 
        /// 对白结束后处理
        /// </summary>
        public int dialogEvent = 0 ;

        /// <summary> 
        /// 模型位置
        /// </summary>
        public string modelPos = string.Empty ;

        /// <summary> 
        /// 模型是否镜像
        /// </summary>
        public int modelMirror = 0 ;

        /// <summary> 
        /// 客户端语言设置
        /// </summary>
        public List<int> languageSet = null ;

        /// <summary> 
        /// 语音
        /// </summary>
        public List<string> soundClient = null ;

        /// <summary> 
        /// 语音
        /// </summary>
        public string sound = string.Empty ;

        /// <summary> 
        /// 文明
        /// </summary>
        public List<int> civilization = null ;

        /// <summary> 
        /// 统帅语音
        /// </summary>
        public List<string> heroSound = null ;

    }
}