// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class GuideDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 阶段
        /// </summary>
        public int stage = 0 ;

        /// <summary> 
        /// 步骤
        /// </summary>
        public int step = 0 ;

        /// <summary> 
        /// 触发参数
        /// </summary>
        public string trigger = string.Empty ;

        /// <summary> 
        /// 引导界面ID
        /// </summary>
        public int uiId = 0 ;

        /// <summary> 
        /// 引导UI组件类型
        /// </summary>
        public int uiType = 0 ;

        /// <summary> 
        /// 节点路径
        /// </summary>
        public string path = string.Empty ;

        /// <summary> 
        /// list项索引
        /// </summary>
        public int listIndex = 0 ;

        /// <summary> 
        /// 查找方式
        /// </summary>
        public int findWay = 0 ;

        /// <summary> 
        /// 引导节点
        /// </summary>
        public string guideNode = string.Empty ;

        /// <summary> 
        /// 引导节点类型
        /// </summary>
        public int guideNodeType = 0 ;

        /// <summary> 
        /// 引导特效挂点
        /// </summary>
        public string guideEffectPos = string.Empty ;

        /// <summary> 
        /// 引导箭头方向
        /// </summary>
        public int guideArrowhead = 0 ;

        /// <summary> 
        /// 引导箭头方向(阿语）
        /// </summary>
        public int guideArrowheadAr = 0 ;

        /// <summary> 
        /// 引导剧情
        /// </summary>
        public int guideDialog = 0 ;

        /// <summary> 
        /// tips语言包
        /// </summary>
        public int l_guideTipsID = 0 ;

        /// <summary> 
        /// 引导过程显示的UI
        /// </summary>
        public List<int> showUi = null ;

        /// <summary> 
        /// tips方向
        /// </summary>
        public int guideTipsPos = 0 ;

        /// <summary> 
        /// tips方向（阿语）
        /// </summary>
        public int guideTipsPosAr = 0 ;

        /// <summary> 
        /// 客户端语言环境
        /// </summary>
        public List<int> languageSet = null ;

        /// <summary> 
        /// 语言版本音效
        /// </summary>
        public List<string> soundClient = null ;

        /// <summary> 
        /// 音效
        /// </summary>
        public string sound = string.Empty ;

        /// <summary> 
        /// 文明
        /// </summary>
        public List<int> civilization = null ;

        /// <summary> 
        /// 文明音效
        /// </summary>
        public List<string> heroSound = null ;

        /// <summary> 
        /// 区域引导
        /// </summary>
        public int guideArena = 0 ;

    }
}