// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class HelpTipsDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 模板语言包
        /// </summary>
        public int l_typeID = 0 ;

        /// <summary> 
        /// tips底图宽度
        /// </summary>
        public int width = 0 ;

        /// <summary> 
        /// 参数{0}语言包
        /// </summary>
        public int l_data1 = 0 ;

        /// <summary> 
        /// 参数{1}语言包
        /// </summary>
        public int l_data2 = 0 ;

        /// <summary> 
        /// 参数{2}语言包
        /// </summary>
        public int l_data3 = 0 ;

        /// <summary> 
        /// 参数{3}语言包
        /// </summary>
        public int l_data4 = 0 ;

        /// <summary> 
        /// 参数{4}语言包
        /// </summary>
        public int l_data5 = 0 ;

    }
}