// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class HeroStarExpDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 稀有度
        /// </summary>
        public int rareGroup = 0 ;

        /// <summary> 
        /// 道具ID
        /// </summary>
        public int itemID = 0 ;

        /// <summary> 
        /// 获得经验值
        /// </summary>
        public int exp = 0 ;

        /// <summary> 
        /// 获得幸运值
        /// </summary>
        public int lucky = 0 ;

        /// <summary> 
        /// 是否为稀有材料，1=是
        /// </summary>
        public int sure = 0 ;

    }
}