// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class HeroTalentGainTreeDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 天赋树组ID
        /// </summary>
        public int gainTree = 0 ;

        /// <summary> 
        /// 天赋等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 战力
        /// </summary>
        public int score = 0 ;

        /// <summary> 
        /// 天赋图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 天赋名字语言包
        /// </summary>
        public int nameID = 0 ;

        /// <summary> 
        /// 天赋效果描述语言包
        /// </summary>
        public int descID = 0 ;

        /// <summary> 
        /// 战斗内生效技能
        /// </summary>
        public int battleSkillID = 0 ;

        /// <summary> 
        /// 属性类型（客户端）
        /// </summary>
        public List<attrType> attrTypeNew = null ;

        /// <summary> 
        /// 属性类型（服务端）
        /// </summary>
        public List<string> attrType = null ;

        /// <summary> 
        /// 属性值
        /// </summary>
        public List<int> attrNumber = null ;

    }
}