// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class HeroTalentDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 天赋语言包
        /// </summary>
        public int l_talentID = 0 ;

        /// <summary> 
        /// 天赋图标小
        /// </summary>
        public string icon1 = string.Empty ;

        /// <summary> 
        /// 增益树
        /// </summary>
        public string gainTree = string.Empty ;

        /// <summary> 
        /// 天赋专精组ID
        /// </summary>
        public int masteryGroupID = 0 ;

        /// <summary> 
        /// tips语言包
        /// </summary>
        public int l_tipsID = 0 ;

        /// <summary> 
        /// 天赋类型
        /// </summary>
        public int type = 0 ;

    }
}