// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class HeroTalentMasteryDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 增益树组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 天赋等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 激活战力
        /// </summary>
        public int score = 0 ;

        /// <summary> 
        /// 专精名称语言包
        /// </summary>
        public int name = 0 ;

        /// <summary> 
        /// 专精效果描述语言包
        /// </summary>
        public int descID = 0 ;

        /// <summary> 
        /// 激活需要天赋点数
        /// </summary>
        public int needTalentPoint = 0 ;

        /// <summary> 
        /// 战斗内生效技能
        /// </summary>
        public int battleSkillID = 0 ;

        /// <summary> 
        /// 属性类型（客户端）
        /// </summary>
        public List<attrType> attrTypeNew = null ;

        /// <summary> 
        /// 属性类型（服务端）
        /// </summary>
        public List<string> attrType = null ;

        /// <summary> 
        /// 属性值
        /// </summary>
        public List<int> attrNumber = null ;

    }
}