// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class HeroSkillLevelDefine
    {
        /// <summary> 
        /// ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 第X次升级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 橙所需道具数量
        /// </summary>
        public int costItem5 = 0 ;

        /// <summary> 
        /// 紫所需道具数量
        /// </summary>
        public int costItem4 = 0 ;

        /// <summary> 
        /// 蓝所需道具数量
        /// </summary>
        public int costItem3 = 0 ;

        /// <summary> 
        /// 绿所需道具数量
        /// </summary>
        public int costItem2 = 0 ;

        /// <summary> 
        /// 白所需道具数量
        /// </summary>
        public int costItem1 = 0 ;

    }
}