// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class HeroTalentTypeDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 天赋语言包
        /// </summary>
        public int l_talentID = 0 ;

        /// <summary> 
        /// 天赋图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 装备天赋图标
        /// </summary>
        public string equipIcon = string.Empty ;

    }
}