// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class HeroDefine
    {
        /// <summary> 
        /// 英雄ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 名称语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 所属文明
        /// </summary>
        public int civilization = 0 ;

        /// <summary> 
        /// 称号语言包
        /// </summary>
        public int l_appellationID = 0 ;

        /// <summary> 
        /// 初始星级
        /// </summary>
        public int initStar = 0 ;

        /// <summary> 
        /// 星级上限
        /// </summary>
        public int star = 0 ;

        /// <summary> 
        /// 稀有度
        /// </summary>
        public int rare = 0 ;

        /// <summary> 
        /// 英雄描述语言包
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 基础战力
        /// </summary>
        public int score = 0 ;

        /// <summary> 
        /// 招募所需道具
        /// </summary>
        public int getItem = 0 ;

        /// <summary> 
        /// 招募所需道具数量
        /// </summary>
        public int getItemNum = 0 ;

        /// <summary> 
        /// 招募所需道具兑换,0=不可以
        /// </summary>
        public int exchange = 0 ;

        /// <summary> 
        /// 英雄特色语言语言包
        /// </summary>
        public List<int> l_heroLanguage = null ;

        /// <summary> 
        /// 解锁天数条件
        /// </summary>
        public int getLimit = 0 ;

        /// <summary> 
        /// 技能
        /// </summary>
        public List<int> skill = null ;

        /// <summary> 
        /// 天赋
        /// </summary>
        public List<int> talent = null ;

        /// <summary> 
        /// 是否显示在英雄列表中,1=不显示
        /// </summary>
        public int listDisplay = 0 ;

        /// <summary> 
        /// 英雄头像
        /// </summary>
        public string heroIcon = string.Empty ;

        /// <summary> 
        /// 英雄模型
        /// </summary>
        public string heroModel = string.Empty ;

        /// <summary> 
        /// 序列帧动画
        /// </summary>
        public string heroAction = string.Empty ;

        /// <summary> 
        /// 英雄场景
        /// </summary>
        public string heroScene = string.Empty ;

        /// <summary> 
        /// 英雄场景召唤镜头
        /// </summary>
        public List<float> heroScenePoint = null ;

        /// <summary> 
        /// 开场白语音
        /// </summary>
        public string voiceOpening = string.Empty ;

        /// <summary> 
        /// 选中语音
        /// </summary>
        public string voiceSelect = string.Empty ;

        /// <summary> 
        /// 移动语音
        /// </summary>
        public string voiceMove = string.Empty ;

    }
}