// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class HeroSkillDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 名称语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 类型语言包
        /// </summary>
        public int l_typeID = 0 ;

        /// <summary> 
        /// 技能战斗效果ID
        /// </summary>
        public List<int> skillBattleID = null ;

        /// <summary> 
        /// 怒气需求
        /// </summary>
        public int anger = 0 ;

        /// <summary> 
        /// 解锁条件
        /// </summary>
        public int open = 0 ;

        /// <summary> 
        /// 解锁条件语言包
        /// </summary>
        public int l_openID = 0 ;

        /// <summary> 
        /// 觉醒增强
        /// </summary>
        public int awakenEnhance = 0 ;

        /// <summary> 
        /// 技能图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 升级所需道具
        /// </summary>
        public int levelUpCostItem = 0 ;

        /// <summary> 
        /// 技能描述语言包
        /// </summary>
        public int l_mesID = 0 ;

        /// <summary> 
        /// 数值1
        /// </summary>
        public List<string> lvEffectDate1 = null ;

        /// <summary> 
        /// 升级效果1语言包
        /// </summary>
        public int l_lvEffect1 = 0 ;

        /// <summary> 
        /// 数值2
        /// </summary>
        public List<string> lvEffectDate2 = null ;

        /// <summary> 
        /// 升级效果2语言包
        /// </summary>
        public int l_lvEffect2 = 0 ;

        /// <summary> 
        /// 数值3
        /// </summary>
        public List<string> lvEffectDate3 = null ;

        /// <summary> 
        /// 升级效果3语言包
        /// </summary>
        public int l_lvEffect3 = 0 ;

        /// <summary> 
        /// 数值4
        /// </summary>
        public List<string> lvEffectDate4 = null ;

        /// <summary> 
        /// 升级效果4语言包
        /// </summary>
        public int l_lvEffect4 = 0 ;

        /// <summary> 
        /// 播放的技能特效，所有特效均挂在施法单位上
        /// </summary>
        public string armyEffect = string.Empty ;

        /// <summary> 
        /// 技能音效
        /// </summary>
        public string sound = string.Empty ;

    }
}