// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class HeroLevelDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 稀有度
        /// </summary>
        public int rareGroup = 0 ;

        /// <summary> 
        /// 等级
        /// </summary>
        public int lv = 0 ;

        /// <summary> 
        /// 升至下一级所需经验
        /// </summary>
        public int exp = 0 ;

        /// <summary> 
        /// 达到本级后的总带兵量
        /// </summary>
        public int soldiers = 0 ;

        /// <summary> 
        /// 达到本级后的总战力
        /// </summary>
        public int score = 0 ;

        /// <summary> 
        /// 获得天赋点数
        /// </summary>
        public int starEffectData = 0 ;

    }
}