// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class HeroStarDefine
    {
        /// <summary> 
        /// 星级
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 星级限制的等级上限
        /// </summary>
        public int starLimit = 0 ;

        /// <summary> 
        /// 橙升到下一星所需经验
        /// </summary>
        public int rare5 = 0 ;

        /// <summary> 
        /// 紫升到下一星所需经验
        /// </summary>
        public int rare4 = 0 ;

        /// <summary> 
        /// 蓝升到下一星所需经验
        /// </summary>
        public int rare3 = 0 ;

        /// <summary> 
        /// 绿到下一升星所需经验
        /// </summary>
        public int rare2 = 0 ;

        /// <summary> 
        /// 白升到下一星所需经验
        /// </summary>
        public int rare1 = 0 ;

        /// <summary> 
        /// 星级效果
        /// </summary>
        public int starEffect = 0 ;

        /// <summary> 
        /// 星级效果语言包
        /// </summary>
        public int l_starEffectID = 0 ;

        /// <summary> 
        /// 星级效果参数
        /// </summary>
        public int starEffectData = 0 ;

    }
}