// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class HeroSkillEffectDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 增加战力
        /// </summary>
        public int score = 0 ;

        /// <summary> 
        /// 属性类型（客户端）
        /// </summary>
        public List<attrType> attrTypeNew = null ;

        /// <summary> 
        /// 属性类型（服务端）
        /// </summary>
        public List<string> attrType = null ;

        /// <summary> 
        /// 属性值
        /// </summary>
        public List<int> attrNumber = null ;

    }
}