// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class InitBuildingDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 建筑类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 建筑等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 初始X坐标
        /// </summary>
        public int posX = 0 ;

        /// <summary> 
        /// 初始Y坐标
        /// </summary>
        public int posY = 0 ;

    }
}