// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class instantPriceDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 购买数量
        /// </summary>
        public int num = 0 ;

        /// <summary> 
        /// 宝石价格
        /// </summary>
        public int price = 0 ;

        /// <summary> 
        /// 价格增加
        /// </summary>
        public float priceAdd = 0 ;

    }
}