// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ItemPackageShowDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 奖励类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 道具&参数ID
        /// </summary>
        public int typeData = 0 ;

        /// <summary> 
        /// 数量
        /// </summary>
        public int number = 0 ;

        /// <summary> 
        /// 随机组
        /// </summary>
        public int randomGroup = 0 ;

        /// <summary> 
        /// 随机权重
        /// </summary>
        public int odds = 0 ;

        /// <summary> 
        /// 文明类型限制
        /// </summary>
        public List<int> civilization_limit = null ;

        /// <summary> 
        /// 奖励数量等级增量基础等级
        /// </summary>
        public int numberStep_lv = 0 ;

        /// <summary> 
        /// 每级增量
        /// </summary>
        public int numberStep_increment = 0 ;

        /// <summary> 
        /// 奖励浮动范围最小比例
        /// </summary>
        public int numberFloat_min = 0 ;

        /// <summary> 
        /// 奖励浮动范围最大比例
        /// </summary>
        public int numberFloat_max = 0 ;

        /// <summary> 
        /// 展示类型
        /// </summary>
        public int showType = 0 ;

        /// <summary> 
        /// 奖励组图标
        /// </summary>
        public int showGroupIcon = 0 ;

        /// <summary> 
        /// 来源名称语言包
        /// </summary>
        public int rewardSrcName = 0 ;

    }
}