// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ItemDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 道具名称语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// tips道具名称语言包
        /// </summary>
        public int l_tipsID = 0 ;

        /// <summary> 
        /// 子分组标签
        /// </summary>
        public int subType = 0 ;

        /// <summary> 
        /// 功能分组
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 功能分组语言包
        /// </summary>
        public int l_typeDes = 0 ;

        /// <summary> 
        /// 类型组
        /// </summary>
        public int typeGroup = 0 ;

        /// <summary> 
        /// 道具图标
        /// </summary>
        public string itemIcon = string.Empty ;

        /// <summary> 
        /// 使用等级
        /// </summary>
        public int lv = 0 ;

        /// <summary> 
        /// 品质
        /// </summary>
        public int quality = 0 ;

        /// <summary> 
        /// 是否可批量使用
        /// </summary>
        public int batchUse = 0 ;

        /// <summary> 
        /// 按钮语言包
        /// </summary>
        public int l_buttonDes = 0 ;

        /// <summary> 
        /// 按钮功能
        /// </summary>
        public int itemFunction = 0 ;

        /// <summary> 
        /// 功能参数1
        /// </summary>
        public int data1 = 0 ;

        /// <summary> 
        /// 功能参数2
        /// </summary>
        public int data2 = 0 ;

        /// <summary> 
        /// 道具描述语言包
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 道具描述解析0
        /// </summary>
        public int desData1 = 0 ;

        /// <summary> 
        /// 道具描述解析1
        /// </summary>
        public int desData2 = 0 ;

        /// <summary> 
        /// 图标顶部信息描述语言包
        /// </summary>
        public int l_topID = 0 ;

        /// <summary> 
        /// 图标顶部信息解析
        /// </summary>
        public int topData = 0 ;

        /// <summary> 
        /// 获得途径，关联itemGet表
        /// </summary>
        public List<int> get = null ;

        /// <summary> 
        /// 快捷使用道具价格
        /// </summary>
        public int shortcutPrice = 0 ;

        /// <summary> 
        /// 商城道具价格
        /// </summary>
        public int shopPrice = 0 ;

        /// <summary> 
        /// 是否需要红点提示
        /// </summary>
        public int redDotPrompt = 0 ;

        /// <summary> 
        /// 显示排序
        /// </summary>
        public int rank = 0 ;

    }
}