// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ItemRewardChoiceDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 显示的物品ID
        /// </summary>
        public int item = 0 ;

        /// <summary> 
        /// 显示的数量
        /// </summary>
        public int num = 0 ;

        /// <summary> 
        /// 奖励组
        /// </summary>
        public int reward = 0 ;

    }
}