// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ItemGetDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 名称语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 描述语言包
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 途径图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 功能开启类型
        /// </summary>
        public int openType = 0 ;

        /// <summary> 
        /// 功能开启参数
        /// </summary>
        public int openData = 0 ;

        /// <summary> 
        /// 前往跳转界面
        /// </summary>
        public int openUi = 0 ;

        /// <summary> 
        /// 是否需要返回主界面,1=是
        /// </summary>
        public int closeUi = 0 ;

    }
}