// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class JumpTypeDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 参数1
        /// </summary>
        public int typeData1 = 0 ;

        /// <summary> 
        /// 参数2
        /// </summary>
        public int typeData2 = 0 ;

    }
}