// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class LanguageSetDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 本机语言代码
        /// </summary>
        public string language = string.Empty ;

        /// <summary> 
        /// 语言包ID
        /// </summary>
        public int l_languageID = 0 ;

        /// <summary> 
        /// 手机默认语言编号
        /// </summary>
        public List<int> telephone = null ;

        /// <summary> 
        /// 语言开关,1=开启，0=关闭
        /// </summary>
        public int enumSwitch = 0 ;

        /// <summary> 
        /// 翻译语言代码
        /// </summary>
        public string translate = string.Empty ;

        /// <summary> 
        /// 游戏版本号
        /// </summary>
        public string gameID = string.Empty ;

    }
}