// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class LanguageServerDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int id  { get; set; }

        /// <summary> 
        /// 中文
        /// </summary>
        public string cn = string.Empty ;

        /// <summary> 
        /// 英语
        /// </summary>
        public string en = string.Empty ;

        /// <summary> 
        /// 阿语
        /// </summary>
        public string arabic = string.Empty ;

        /// <summary> 
        /// 土耳其语
        /// </summary>
        public string tr = string.Empty ;

        /// <summary> 
        /// 俄语
        /// </summary>
        public string ru = string.Empty ;

    }
}