// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class LeaderboardDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 名称语言包
        /// </summary>
        public int nameID = 0 ;

        /// <summary> 
        /// 排行榜大类
        /// </summary>
        public int list = 0 ;

        /// <summary> 
        /// 排行对象
        /// </summary>
        public int target = 0 ;

        /// <summary> 
        /// 排行榜类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 排行榜类型名称
        /// </summary>
        public List<int> typeNameID = null ;

        /// <summary> 
        /// 排行榜最大记录数量
        /// </summary>
        public int recordLimit = 0 ;

        /// <summary> 
        /// 排行榜最大显示数量
        /// </summary>
        public int showLimit = 0 ;

        /// <summary> 
        /// 排行榜对比数量（客户端）
        /// </summary>
        public int comparisonLimit = 0 ;

        /// <summary> 
        /// 排行榜限制等级
        /// </summary>
        public List<int> level = null ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 入口图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 背景旗帜
        /// </summary>
        public string flag = string.Empty ;

    }
}