// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MailDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 邮件分页
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 邮件类型组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 名称语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 副标题语言包
        /// </summary>
        public int l_subheadingID = 0 ;

        /// <summary> 
        /// 邮件内容语言包
        /// </summary>
        public int l_mesID = 0 ;

        /// <summary> 
        /// 附件
        /// </summary>
        public int enclosure = 0 ;

        /// <summary> 
        /// 是否需要手动领取附件
        /// </summary>
        public int receiveAuto = 0 ;

        /// <summary> 
        /// 领取附件后是否自动删除
        /// </summary>
        public int deleteAuto = 0 ;

        /// <summary> 
        /// 发件人语言包
        /// </summary>
        public int l_senderID = 0 ;

        /// <summary> 
        /// 邮件操作按钮
        /// </summary>
        public List<int> operate = null ;

        /// <summary> 
        /// 邮件内图片
        /// </summary>
        public string image = string.Empty ;

        /// <summary> 
        /// 邮件头像
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 邮件海报
        /// </summary>
        public string poster = string.Empty ;

        /// <summary> 
        /// 邮件气泡名称语言包
        /// </summary>
        public int messageName = 0 ;

        /// <summary> 
        /// 邮件气泡名称颜色
        /// </summary>
        public string messageNameColor = string.Empty ;

        /// <summary> 
        /// 邮件气泡描述语言包
        /// </summary>
        public int message = 0 ;

    }
}