// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MailLevelLimitDefine
    {
        /// <summary> 
        /// 市政厅等级
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 限制发送邮件数量
        /// </summary>
        public int mailNum = 0 ;

    }
}