// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MapBuildingDataDefine
    {
        /// <summary> 
        /// 系统流水
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 联盟建筑类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 第几座建筑
        /// </summary>
        public int orderNum = 0 ;

        /// <summary> 
        /// 建造速度参数1
        /// </summary>
        public int X1 = 0 ;

        /// <summary> 
        /// 建造速度参数2
        /// </summary>
        public int Y1 = 0 ;

        /// <summary> 
        /// 建造进度上限
        /// </summary>
        public int S = 0 ;

        /// <summary> 
        /// 前置建筑类型1
        /// </summary>
        public int preBuilding1 = 0 ;

        /// <summary> 
        /// 前置建筑数量1
        /// </summary>
        public int preNum1 = 0 ;

        /// <summary> 
        /// 需求联盟人数
        /// </summary>
        public int playerNum = 0 ;

        /// <summary> 
        /// 需求联盟总战力
        /// </summary>
        public int alliancePower = 0 ;

        /// <summary> 
        /// 联盟粮食
        /// </summary>
        public int food = 0 ;

        /// <summary> 
        /// 联盟木材
        /// </summary>
        public int wood = 0 ;

        /// <summary> 
        /// 联盟石材
        /// </summary>
        public int stone = 0 ;

        /// <summary> 
        /// 联盟金币
        /// </summary>
        public int coin = 0 ;

        /// <summary> 
        /// 联盟积分
        /// </summary>
        public int fund = 0 ;

    }
}