// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MapBarrierConnectDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 是否可行走
        /// </summary>
        public int isWalk = 0 ;

        /// <summary> 
        /// 省份编号
        /// </summary>
        public int zoneId = 0 ;

        /// <summary> 
        /// 关卡编号
        /// </summary>
        public int checkPointId = 0 ;

        /// <summary> 
        /// 哪个省份的中心（作废）
        /// </summary>
        public int zoneCenter = 0 ;

    }
}