// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MapEmojiDefine
    {
        /// <summary> 
        /// 系统编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 表情/喊话
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 表情索引
        /// </summary>
        public string imgPath = string.Empty ;

        /// <summary> 
        /// 表情的spine动画预制
        /// </summary>
        public string spine = string.Empty ;

        /// <summary> 
        /// 喊话语言包
        /// </summary>
        public int l_Claim = 0 ;

        /// <summary> 
        /// 默认状态
        /// </summary>
        public int normalState = 0 ;

    }
}