// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MapFixPointDefine
    {
        /// <summary> 
        /// 系统编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 建筑类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 坐标X
        /// </summary>
        public int posX = 0 ;

        /// <summary> 
        /// 坐标Y
        /// </summary>
        public int posY = 0 ;

        /// <summary> 
        /// 分组
        /// </summary>
        public int group = 0 ;

    }
}