// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MapItemTypeDefine
    {
        /// <summary> 
        /// 地图物件类型ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 名称
        /// </summary>
        public int l_nameId = 0 ;

        /// <summary> 
        /// 描述
        /// </summary>
        public int l_desc = 0 ;

        /// <summary> 
        /// 物件类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 指向BUFF
        /// </summary>
        public List<int> buffData = null ;

        /// <summary> 
        /// 模型半径
        /// </summary>
        public float radius = 0 ;

        /// <summary> 
        /// 独占区半径
        /// </summary>
        public float radiusCollide = 0 ;

        /// <summary> 
        /// 存在时间
        /// </summary>
        public int showTime = 0 ;

        /// <summary> 
        /// 绑定光效
        /// </summary>
        public string itemEffectShow = string.Empty ;

        /// <summary> 
        /// 模型索引
        /// </summary>
        public string modelId = string.Empty ;

        /// <summary> 
        /// UI图标
        /// </summary>
        public string headIcon = string.Empty ;

    }
}