// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MapMarkerTypeDefine
    {
        /// <summary> 
        /// 系统编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 标记类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 标记名称语言包
        /// </summary>
        public int l_nameId = 0 ;

        /// <summary> 
        /// 图标图片索引
        /// </summary>
        public string iconImg = string.Empty ;

        /// <summary> 
        /// 联盟标记模型ID
        /// </summary>
        public string modelId = string.Empty ;

        /// <summary> 
        /// 联盟标记光效索引
        /// </summary>
        public string effectShow = string.Empty ;

        /// <summary> 
        /// 联盟标记光效颜色
        /// </summary>
        public string effectColor = string.Empty ;

        /// <summary> 
        /// 标记频道信息语言包ID
        /// </summary>
        public int chatMessage = 0 ;

        /// <summary> 
        /// 标记邮件
        /// </summary>
        public int mail = 0 ;

    }
}