// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MapZoneSFDefine
    {
        /// <summary> 
        /// 区域序号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 省份编号
        /// </summary>
        public int zoneOrder = 0 ;

        /// <summary> 
        /// 关卡拓扑区块编号
        /// </summary>
        public int topZoneID = 0 ;

    }
}