// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MapZoneMaskDefine
    {
        /// <summary> 
        /// 区域序号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int mapZoneId  { get; set; }

    }
}