// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MonsterDamageRewardDefine
    {
        /// <summary> 
        /// 系统流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 伤害奖励计算分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 分组奖励档次
        /// </summary>
        public int stage = 0 ;

        /// <summary> 
        /// 比例数值上限（万分比）
        /// </summary>
        public int damageScale = 0 ;

        /// <summary> 
        /// 奖励编号
        /// </summary>
        public int rewardId = 0 ;

    }
}