// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MonsterZoneLevelDefine
    {
        /// <summary> 
        /// 瓦片序号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 刷怪等级区域
        /// </summary>
        public int zoneLevel = 0 ;

    }
}