// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MonsterRefreshLevelDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 怪物类型分组
        /// </summary>
        public int monsterType = 0 ;

        /// <summary> 
        /// 区域等级
        /// </summary>
        public int zoneLevel = 0 ;

        /// <summary> 
        /// 该等级怪物ID
        /// </summary>
        public int monsterLevel = 0 ;

        /// <summary> 
        /// 最小开服天数
        /// </summary>
        public int serverLevelMin = 0 ;

        /// <summary> 
        /// 最大开服天数
        /// </summary>
        public int serverLevelMax = 0 ;

        /// <summary> 
        /// 出现权重
        /// </summary>
        public int chance = 0 ;

    }
}