// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MonsterDefine
    {
        /// <summary> 
        /// 怪物ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 名称语言包
        /// </summary>
        public int l_nameId = 0 ;

        /// <summary> 
        /// 怪物描述语言包
        /// </summary>
        public int l_descId = 0 ;

        /// <summary> 
        /// 怪物类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 怪物等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 战斗阵容ID
        /// </summary>
        public int monsterTroopsId = 0 ;

        /// <summary> 
        /// 是否自动复原
        /// </summary>
        public int recover = 0 ;

        /// <summary> 
        /// 击杀奖励
        /// </summary>
        public int killReward = 0 ;

        /// <summary> 
        /// 击杀经验奖励
        /// </summary>
        public int killExp = 0 ;

        /// <summary> 
        /// 掉落规则
        /// </summary>
        public int lootReward = 0 ;

        /// <summary> 
        /// 展示奖励
        /// </summary>
        public int showReward = 0 ;

        /// <summary> 
        /// 伤害奖励
        /// </summary>
        public int damageReward = 0 ;

        /// <summary> 
        /// 联盟礼物
        /// </summary>
        public int allianceGift = 0 ;

        /// <summary> 
        /// 消耗行动力
        /// </summary>
        public int costAP = 0 ;

        /// <summary> 
        /// 是否可集结
        /// </summary>
        public int ifRally = 0 ;

        /// <summary> 
        /// 集结消耗行动力
        /// </summary>
        public int rallyAP = 0 ;

        /// <summary> 
        /// 怪物倒计时
        /// </summary>
        public int showTime = 0 ;

        /// <summary> 
        /// 占据空间半径
        /// </summary>
        public float radius = 0 ;

        /// <summary> 
        /// 独占区域半径
        /// </summary>
        public float radiusCollide = 0 ;

        /// <summary> 
        /// 怪物警戒范围
        /// </summary>
        public int monsterVigilanceRange = 0 ;

        /// <summary> 
        /// 追击距离（乘100）
        /// </summary>
        public int battleFollowDistance = 0 ;

        /// <summary> 
        /// 战斗半径
        /// </summary>
        public int battleRadius = 0 ;

        /// <summary> 
        /// 巡逻半径
        /// </summary>
        public int patrolRadius = 0 ;

        /// <summary> 
        /// 搜索半径
        /// </summary>
        public int refreshRadius = 0 ;

        /// <summary> 
        /// 推荐战斗力
        /// </summary>
        public int powerAdvise = 0 ;

        /// <summary> 
        /// 推荐的玩家兵力数量
        /// </summary>
        public int armCnt = 0 ;

        /// <summary> 
        /// 推荐的玩家兵种等级
        /// </summary>
        public int armLevel = 0 ;

        /// <summary> 
        /// 怪物AI
        /// </summary>
        public int monsterAI = 0 ;

        /// <summary> 
        /// 怪物头像
        /// </summary>
        public string headIcon = string.Empty ;

        /// <summary> 
        /// 邮件头像
        /// </summary>
        public string mailIcon = string.Empty ;

        /// <summary> 
        /// 缩略图
        /// </summary>
        public string mapIcon = string.Empty ;

        /// <summary> 
        /// 下标图标索引
        /// </summary>
        public string subscriptIcon = string.Empty ;

        /// <summary> 
        /// 模型
        /// </summary>
        public string modelId = string.Empty ;

        /// <summary> 
        /// 奖励发放邮件
        /// </summary>
        public int emailId = 0 ;

        /// <summary> 
        /// 作废
        /// </summary>
        public int emailId2 = 0 ;

        /// <summary> 
        /// 作废
        /// </summary>
        public int emailId3 = 0 ;

        /// <summary> 
        /// 巡逻时间最小间隔（毫秒）
        /// </summary>
        public int patrolTimeCD = 0 ;

        /// <summary> 
        /// 移动速度（乘100）
        /// </summary>
        public int patrolSpeed = 0 ;

        /// <summary> 
        /// 巡逻时间最大间隔（毫秒）移动速度
        /// </summary>
        public int patrolTimeCdMax = 0 ;

        /// <summary> 
        /// 神秘商人减少CD
        /// </summary>
        public float mysteryStoreCD = 0 ;

        /// <summary> 
        /// 解锁纪念碑事件编号
        /// </summary>
        public int openMileStone = 0 ;

        /// <summary> 
        /// 召唤怪挑战类型
        /// </summary>
        public int battleType = 0 ;

    }
}