// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MonsterTroopsAttrDefine
    {
        /// <summary> 
        /// 军队构成编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 士兵部队分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 士兵类型
        /// </summary>
        public int armType = 0 ;

        /// <summary> 
        /// 士兵数量
        /// </summary>
        public int armNum = 0 ;

        /// <summary> 
        /// 攻击
        /// </summary>
        public int attack = 0 ;

        /// <summary> 
        /// 防御
        /// </summary>
        public int defence = 0 ;

        /// <summary> 
        /// 血量
        /// </summary>
        public int hp = 0 ;

    }
}