// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MonsterLootRuleDefine
    {
        /// <summary> 
        /// 系统流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 掉落规则组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 掉落类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 掉落物件ID
        /// </summary>
        public int mapItemId = 0 ;

        /// <summary> 
        /// 奖励组ID
        /// </summary>
        public int reward = 0 ;

        /// <summary> 
        /// 概率权重
        /// </summary>
        public int rate = 0 ;

    }
}