// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MysteryStoreDefine
    {
        /// <summary> 
        /// 商品ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 道具ID
        /// </summary>
        public int item = 0 ;

        /// <summary> 
        /// 货币类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 原价
        /// </summary>
        public int price = 0 ;

        /// <summary> 
        /// 刷新等级限制
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 出现概率
        /// </summary>
        public int prob = 0 ;

        /// <summary> 
        /// 折扣组
        /// </summary>
        public int discount = 0 ;

        /// <summary> 
        /// 个数组
        /// </summary>
        public int num = 0 ;

    }
}