// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class MysteryStoreProDefine
    {
        /// <summary> 
        /// ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 参数
        /// </summary>
        public int add = 0 ;

        /// <summary> 
        /// 概率
        /// </summary>
        public int probability = 0 ;

    }
}