// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class OpenUiDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 界面名称
        /// </summary>
        public int nameID = 0 ;

        /// <summary> 
        /// 系统功能开启
        /// </summary>
        public int systemOpen = 0 ;

        /// <summary> 
        /// 建筑类型
        /// </summary>
        public int buildType = 0 ;

        /// <summary> 
        /// 活动开启
        /// </summary>
        public List<int> activity = null ;

        /// <summary> 
        /// 充值开启
        /// </summary>
        public int recharge = 0 ;

        /// <summary> 
        /// 礼包开启
        /// </summary>
        public int pakege = 0 ;

    }
}