// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class OpenLodUiDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 界面模块名称
        /// </summary>
        public string uiName = string.Empty ;

        /// <summary> 
        /// 界面模块预制
        /// </summary>
        public string uiId = string.Empty ;

        /// <summary> 
        /// 内城级
        /// </summary>
        public int City = 0 ;

        /// <summary> 
        /// 外城1级
        /// </summary>
        public int Tactical = 0 ;

        /// <summary> 
        /// 外城2级
        /// </summary>
        public int TacticsToStrategy_1 = 0 ;

        /// <summary> 
        /// 外城3级
        /// </summary>
        public int TacticsToStrategy_2 = 0 ;

        /// <summary> 
        /// 战略（预览）级
        /// </summary>
        public int Strategic = 0 ;

        /// <summary> 
        /// 王国级
        /// </summary>
        public int NationWide = 0 ;

        /// <summary> 
        /// 大陆级
        /// </summary>
        public int Continental = 0 ;

        /// <summary> 
        /// 默认窗口
        /// </summary>
        public int openWinDefault = 0 ;

        /// <summary> 
        /// 选择部队与斥候窗口
        /// </summary>
        public int openWinCreateTroops = 0 ;

        /// <summary> 
        /// 搜索窗口
        /// </summary>
        public int openWinSearch = 0 ;

        /// <summary> 
        /// NPC对话窗口
        /// </summary>
        public int openWinNpcDialog = 0 ;

        /// <summary> 
        /// 默认动画
        /// </summary>
        public string Animator = string.Empty ;

        /// <summary> 
        /// 显示条件（新手引导步骤）
        /// </summary>
        public int guideStage = 0 ;

        /// <summary> 
        /// 非阿语动画
        /// </summary>
        public string unArbAnimator = string.Empty ;

        /// <summary> 
        /// 时代变化显示
        /// </summary>
        public int ageUpdate = 0 ;

    }
}