// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class PlayerHeadDefine
    {
        /// <summary> 
        /// ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 名称语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 描述语言包
        /// </summary>
        public int l_decID = 0 ;

        /// <summary> 
        /// 获取
        /// </summary>
        public int get = 0 ;

        /// <summary> 
        /// 标签语言包
        /// </summary>
        public int l_tagID = 0 ;

        /// <summary> 
        /// 初始
        /// </summary>
        public int initial = 0 ;

        /// <summary> 
        /// 图标
        /// </summary>
        public string icon = string.Empty ;

    }
}