// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class PriceDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包id
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 价格，美元
        /// </summary>
        public float price = 0 ;

        /// <summary> 
        /// 充值类型
        /// </summary>
        public int rechargeType = 0 ;

        /// <summary> 
        /// 对应表ID
        /// </summary>
        public int rechargeTypeID = 0 ;

        /// <summary> 
        /// 商品id
        /// </summary>
        public int rechargeID = 0 ;

        /// <summary> 
        /// 商品购买成功后的提示语
        /// </summary>
        public int l_succeededID = 0 ;

    }
}