// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class PushMessageDataDefine
    {
        /// <summary> 
        /// 消息编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 消息分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 是否合并
        /// </summary>
        public int mergeType = 0 ;

        /// <summary> 
        /// 中文内容
        /// </summary>
        public string cnMessage = string.Empty ;

        /// <summary> 
        /// 英文内容
        /// </summary>
        public string enMessage = string.Empty ;

        /// <summary> 
        /// 阿语内容
        /// </summary>
        public string arabicMessage = string.Empty ;

        /// <summary> 
        /// 土耳其内容
        /// </summary>
        public string trMessage = string.Empty ;

        /// <summary> 
        /// 俄语内容
        /// </summary>
        public string ruMessage = string.Empty ;

    }
}