// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class PushMessageGroupDefine
    {
        /// <summary> 
        /// 消息分组
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 分组标题
        /// </summary>
        public int l_title = 0 ;

        /// <summary> 
        /// 分组描述
        /// </summary>
        public int l_desc = 0 ;

        /// <summary> 
        /// 默认推送状态
        /// </summary>
        public int pushDefault = 0 ;

    }
}