// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class QualitySetDefine
    {
        /// <summary> 
        /// 功能ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 设置类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 低
        /// </summary>
        public int quality1 = 0 ;

        /// <summary> 
        /// 
        /// </summary>
        public int quality2 = 0 ;

        /// <summary> 
        /// 高
        /// </summary>
        public int quality3 = 0 ;

    }
}