// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class RallyTimesDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 集结类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 集结时间1
        /// </summary>
        public int rallyTime1 = 0 ;

        /// <summary> 
        /// 集结时间2
        /// </summary>
        public int rallyTime2 = 0 ;

        /// <summary> 
        /// 集结时间3
        /// </summary>
        public int rallyTime3 = 0 ;

        /// <summary> 
        /// 集结时间4
        /// </summary>
        public int rallyTime4 = 0 ;

    }
}