// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class RechargeGemMallDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 商品价格索引
        /// </summary>
        public int price = 0 ;

        /// <summary> 
        /// 充值宝石数
        /// </summary>
        public int denarNum = 0 ;

        /// <summary> 
        /// 首次购买赠送
        /// </summary>
        public int firstPresenter = 0 ;

        /// <summary> 
        /// 第二次之后购买赠送
        /// </summary>
        public int presenter = 0 ;

        /// <summary> 
        /// icon
        /// </summary>
        public string gemIcon = string.Empty ;

        /// <summary> 
        /// 给与崛起之路的进度
        /// </summary>
        public int rechargeProgress = 0 ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int mail = 0 ;

    }
}