// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class RechargeSaleDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 礼包组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 档位
        /// </summary>
        public int gears = 0 ;

        /// <summary> 
        /// 商品价格索引
        /// </summary>
        public int price = 0 ;

        /// <summary> 
        /// 礼包类型
        /// </summary>
        public int giftType = 0 ;

        /// <summary> 
        /// 参数1
        /// </summary>
        public string data1 = string.Empty ;

        /// <summary> 
        /// 参数2
        /// </summary>
        public int data2 = 0 ;

        /// <summary> 
        /// 奖励组
        /// </summary>
        public int itemPackage = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_desID1 = 0 ;

        /// <summary> 
        /// 文本解析
        /// </summary>
        public int desData1 = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_desID2 = 0 ;

        /// <summary> 
        /// 文本解析
        /// </summary>
        public int desData2 = 0 ;

        /// <summary> 
        /// 打折标签语言包ID
        /// </summary>
        public int l_discountID = 0 ;

        /// <summary> 
        /// 解析
        /// </summary>
        public int discountData = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_labelID = 0 ;

        /// <summary> 
        /// 底图
        /// </summary>
        public string background = string.Empty ;

        /// <summary> 
        /// 横幅颜色配置
        /// </summary>
        public string bannerColour = string.Empty ;

        /// <summary> 
        /// 底板使用资源
        /// </summary>
        public string baseRes = string.Empty ;

        /// <summary> 
        /// 给与崛起之路的进度
        /// </summary>
        public int rechargeProgress = 0 ;

        /// <summary> 
        /// 邮件id
        /// </summary>
        public int mailID = 0 ;

    }
}