// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class RechargeDailySpecialDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 商品价格索引
        /// </summary>
        public int price = 0 ;

        /// <summary> 
        /// 统帅限制
        /// </summary>
        public List<int> heroLimit = null ;

        /// <summary> 
        /// 奖励索引
        /// </summary>
        public List<int> itemPackage = null ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 礼包价值
        /// </summary>
        public int giftValue = 0 ;

        /// <summary> 
        /// 图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 给与崛起之路的进度
        /// </summary>
        public int rechargeProgress = 0 ;

        /// <summary> 
        /// 邮件id
        /// </summary>
        public int mailID = 0 ;

    }
}