// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class RechargeLimitTimeBagDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 商品价格索引
        /// </summary>
        public int price = 0 ;

        /// <summary> 
        /// 触发类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 参数1
        /// </summary>
        public int data1 = 0 ;

        /// <summary> 
        /// 参数2
        /// </summary>
        public int data2 = 0 ;

        /// <summary> 
        /// 触发限制等级区间
        /// </summary>
        public int limitLvMin = 0 ;

        /// <summary> 
        /// 触发限制等级区间
        /// </summary>
        public int limitLvMax = 0 ;

        /// <summary> 
        /// 礼包触发次数
        /// </summary>
        public int limitTime = 0 ;

        /// <summary> 
        /// 持续时间（秒）
        /// </summary>
        public int time = 0 ;

        /// <summary> 
        /// 奖励组
        /// </summary>
        public int itemPackage = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 描述解析1
        /// </summary>
        public int desData1 = 0 ;

        /// <summary> 
        /// 描述解析2
        /// </summary>
        public int desData2 = 0 ;

        /// <summary> 
        /// 背景图
        /// </summary>
        public string background = string.Empty ;

        /// <summary> 
        /// 入口图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 入口图标底框
        /// </summary>
        public string iconBorder = string.Empty ;

        /// <summary> 
        /// 邮件id
        /// </summary>
        public int mailID = 0 ;

    }
}