// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class RechargeFirstDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 前置活动
        /// </summary>
        public int frontID = 0 ;

        /// <summary> 
        /// 后置活动
        /// </summary>
        public int nextID = 0 ;

        /// <summary> 
        /// 类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 商品价格索引
        /// </summary>
        public int price = 0 ;

        /// <summary> 
        /// 需求宝石
        /// </summary>
        public int needDenar = 0 ;

        /// <summary> 
        /// 奖励组
        /// </summary>
        public int itemPackage = 0 ;

        /// <summary> 
        /// 关联vip
        /// </summary>
        public int vipSpecialBox = 0 ;

        /// <summary> 
        /// 模型展示
        /// </summary>
        public int heroShow = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 礼包价值
        /// </summary>
        public int giftValue = 0 ;

        /// <summary> 
        /// 背景图
        /// </summary>
        public string background = string.Empty ;

        /// <summary> 
        /// 邮件id
        /// </summary>
        public int mailID = 0 ;

        /// <summary> 
        /// 跳转类型
        /// </summary>
        public int jumpType = 0 ;

    }
}