// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class RechargeSupplyDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 商品价格索引
        /// </summary>
        public int price = 0 ;

        /// <summary> 
        /// 直接给予的宝石
        /// </summary>
        public int giveGem = 0 ;

        /// <summary> 
        /// 持续天数
        /// </summary>
        public int continueDays = 0 ;

        /// <summary> 
        /// 奖励组
        /// </summary>
        public int itemPackage = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 描述解析
        /// </summary>
        public int desData = 0 ;

        /// <summary> 
        /// 图片
        /// </summary>
        public string background = string.Empty ;

        /// <summary> 
        /// 给与崛起之路的进度
        /// </summary>
        public int rechargeProgress = 0 ;

        /// <summary> 
        /// 补发邮件
        /// </summary>
        public int mailID = 0 ;

    }
}