// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class RechargeListDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 分页名称
        /// </summary>
        public int l_pagingID = 0 ;

        /// <summary> 
        /// 分页类型
        /// </summary>
        public int pagingType = 0 ;

        /// <summary> 
        /// 前置类型
        /// </summary>
        public int preposition = 0 ;

        /// <summary> 
        /// 开启时间
        /// </summary>
        public string timeType = string.Empty ;

        /// <summary> 
        /// 具体时间
        /// </summary>
        public string startTime = string.Empty ;

        /// <summary> 
        /// 持续时间（秒）
        /// </summary>
        public int durationTime = 0 ;

        /// <summary> 
        /// 排序
        /// </summary>
        public int sort = 0 ;

        /// <summary> 
        /// HUD主界面图标
        /// </summary>
        public string icon = string.Empty ;

    }
}