// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ResourceGatherTypeDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 资源点类型名称
        /// </summary>
        public int l_nameId = 0 ;

        /// <summary> 
        /// 资源点描述文字
        /// </summary>
        public int l_descId = 0 ;

        /// <summary> 
        /// 资源点描述文字2
        /// </summary>
        public int l_descId2 = 0 ;

        /// <summary> 
        /// 资源点类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 资源点等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 前置科技类型要求
        /// </summary>
        public int scienceReq = 0 ;

        /// <summary> 
        /// 前置科技等级要求
        /// </summary>
        public int scienceLevReq = 0 ;

        /// <summary> 
        /// 默认采集速度/小时
        /// </summary>
        public int collectSpeed = 0 ;

        /// <summary> 
        /// 储量上限
        /// </summary>
        public int resAmount = 0 ;

        /// <summary> 
        /// 存在时间
        /// </summary>
        public int timeLimit = 0 ;

        /// <summary> 
        /// 半径空间
        /// </summary>
        public int radius = 0 ;

        /// <summary> 
        /// 模型资源
        /// </summary>
        public string modelId = string.Empty ;

        /// <summary> 
        /// Lod模型资源（作废）
        /// </summary>
        public string modelIdLod = string.Empty ;

        /// <summary> 
        /// Lod模型资源2
        /// </summary>
        public string modelIdLod2 = string.Empty ;

        /// <summary> 
        /// 资源图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 详情界面图标
        /// </summary>
        public string iconRes = string.Empty ;

        /// <summary> 
        /// 地图缩略图
        /// </summary>
        public string mapIconRes = string.Empty ;

        /// <summary> 
        /// 邮件
        /// </summary>
        public int mail = 0 ;

    }
}