// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ResourceGatherPointDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 资源点坐标X
        /// </summary>
        public int posX = 0 ;

        /// <summary> 
        /// 资源点坐标Y
        /// </summary>
        public int posY = 0 ;

    }
}