// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ResourcesPlunderLossDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 被掠夺城市市政厅等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 损耗系数
        /// </summary>
        public int lossConstant = 0 ;

    }
}