// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ResourceGatherRuleDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 规则分组
        /// </summary>
        public int ruleId = 0 ;

        /// <summary> 
        /// 资源点类型
        /// </summary>
        public int resourceGatherType = 0 ;

        /// <summary> 
        /// 资源点等级
        /// </summary>
        public int resourceGatherLevel = 0 ;

        /// <summary> 
        /// 期望数量
        /// </summary>
        public int resourceGatherCnt = 0 ;

    }
}