// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class ServerListTypeDefine
    {
        /// <summary> 
        /// 流水号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 服务器ID
        /// </summary>
        public int severId = 0 ;

        /// <summary> 
        /// 服务器文字ID
        /// </summary>
        public int serverNameId = 0 ;

        /// <summary> 
        /// 开服时间YYYYMMDDHHMM
        /// </summary>
        public string serverTime = string.Empty ;

        /// <summary> 
        /// 是否显示
        /// </summary>
        public int IsDisplay = 0 ;

        /// <summary> 
        /// 组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 组名
        /// </summary>
        public int groupNameId = 0 ;

        /// <summary> 
        /// 排序
        /// </summary>
        public int order = 0 ;

        /// <summary> 
        /// 版本号
        /// </summary>
        public string version = string.Empty ;

    }
}