// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class SettingPersonalityDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 功能语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 描述语言包
        /// </summary>
        public int l_decID = 0 ;

        /// <summary> 
        /// 默认开关,1=开启，0=关闭
        /// </summary>
        public int open = 0 ;

        /// <summary> 
        /// 重置时间，单位秒
        /// </summary>
        public int resetTiem = 0 ;

        /// <summary> 
        /// 是否显示在列表中,1=显示，0=关闭
        /// </summary>
        public int display = 0 ;

        /// <summary> 
        /// 排序
        /// </summary>
        public int order = 0 ;

    }
}