// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class SkillBattleDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 规则组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 技能触发部队条件
        /// </summary>
        public int autoTroopsCondition = 0 ;

        /// <summary> 
        /// 部队兵种构成限制
        /// </summary>
        public int autoArmsType = 0 ;

        /// <summary> 
        /// 部队兵种构成参数
        /// </summary>
        public int autoArmsParm = 0 ;

        /// <summary> 
        /// 部队兵力类型
        /// </summary>
        public int autoArmsNumType = 0 ;

        /// <summary> 
        /// 部队兵力参数
        /// </summary>
        public int autoArmsNumParm = 0 ;

        /// <summary> 
        /// 被动技能时机
        /// </summary>
        public int autoActive = 0 ;

        /// <summary> 
        /// 技能被动触发参数
        /// </summary>
        public int autoActiveParm = 0 ;

        /// <summary> 
        /// 被动技能触发概率
        /// </summary>
        public int autoActivePro = 0 ;

        /// <summary> 
        /// 触发次数限制
        /// </summary>
        public int autoActiveRate = 0 ;

        /// <summary> 
        /// 触发回合间隔
        /// </summary>
        public int autoActiveInterval = 0 ;

        /// <summary> 
        /// 技能目标类型
        /// </summary>
        public int targetType = 0 ;

        /// <summary> 
        /// 目标条件参数
        /// </summary>
        public List<int> targetParm = null ;

        /// <summary> 
        /// 技能范围类型
        /// </summary>
        public int rangeType = 0 ;

        /// <summary> 
        /// 扇形半径
        /// </summary>
        public int skillRadius = 0 ;

        /// <summary> 
        /// 技能释放角度
        /// </summary>
        public int skillAngle = 0 ;

        /// <summary> 
        /// 技能额外目标数量上限
        /// </summary>
        public int targetExMaxNum = 0 ;

        /// <summary> 
        /// 技能系数
        /// </summary>
        public int dmgPower = 0 ;

        /// <summary> 
        /// 多目标技能伤害系数
        /// </summary>
        public List<int> moreDmgPower = null ;

        /// <summary> 
        /// 技能治疗系数
        /// </summary>
        public int healPower = 0 ;

        /// <summary> 
        /// 技能怒气恢复类型
        /// </summary>
        public int angerRecoveryType = 0 ;

        /// <summary> 
        /// 怒气参数
        /// </summary>
        public int angerParm = 0 ;

        /// <summary> 
        /// 技能效果ID
        /// </summary>
        public List<int> statusID = null ;

        /// <summary> 
        /// 清除状态类型
        /// </summary>
        public int statusDelType = 0 ;

        /// <summary> 
        /// 清除ID
        /// </summary>
        public List<int> statusDelID = null ;

        /// <summary> 
        /// 清除状态数量上限
        /// </summary>
        public int statusDelMaxNumber = 0 ;

        /// <summary> 
        /// 状态清除成功率
        /// </summary>
        public int delRate = 0 ;

    }
}