// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class SkillStatusDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 名称
        /// </summary>
        public string name = string.Empty ;

        /// <summary> 
        /// 名称语言包
        /// </summary>
        public int nameID = 0 ;

        /// <summary> 
        /// 描述
        /// </summary>
        public string desc = string.Empty ;

        /// <summary> 
        /// 描述语言包
        /// </summary>
        public int descID = 0 ;

        /// <summary> 
        /// 状态生效时显示语言包
        /// </summary>
        public int showIcon = 0 ;

        /// <summary> 
        /// 状态生效时显示特效
        /// </summary>
        public string showEffect = string.Empty ;

        /// <summary> 
        /// 是否怒气技能
        /// </summary>
        public int isAngerSkill = 0 ;

        /// <summary> 
        /// 类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// BUF是否在战斗外生效
        /// </summary>
        public int battleEffectType = 0 ;

        /// <summary> 
        /// 状态类型
        /// </summary>
        public int buffType = 0 ;

        /// <summary> 
        /// 状态命中率
        /// </summary>
        public int hitRate = 0 ;

        /// <summary> 
        /// 状态基础回合数
        /// </summary>
        public int boutTimes = 0 ;

        /// <summary> 
        /// 状态波动回合数
        /// </summary>
        public int boutTimesWave = 0 ;

        /// <summary> 
        /// 状态叠加类型
        /// </summary>
        public int overlayType = 0 ;

        /// <summary> 
        /// 状态共存规则
        /// </summary>
        public int coexistRule = 0 ;

        /// <summary> 
        /// 状态叠加层数上限
        /// </summary>
        public int overlay = 0 ;

        /// <summary> 
        /// 是否刷新回合数
        /// </summary>
        public int refreshRoundRule = 0 ;

        /// <summary> 
        /// 状态清除规则
        /// </summary>
        public int delRule = 0 ;

        /// <summary> 
        /// 沉默类型
        /// </summary>
        public int silentType = 0 ;

        /// <summary> 
        /// 沉默概率
        /// </summary>
        public int silentRate = 0 ;

        /// <summary> 
        /// 状态免疫类型
        /// </summary>
        public int immuneType = 0 ;

        /// <summary> 
        /// 状态免疫概率
        /// </summary>
        public int immuneRate = 0 ;

        /// <summary> 
        /// 影响属性类型
        /// </summary>
        public List<string> attrType = null ;

        /// <summary> 
        /// 每层效果影响属性数值
        /// </summary>
        public List<int> attrNumber = null ;

        /// <summary> 
        /// 状态伤害及治疗触发时机
        /// </summary>
        public int statusMoment = 0 ;

        /// <summary> 
        /// 每层状态伤害系数
        /// </summary>
        public int statusDamagePower = 0 ;

        /// <summary> 
        /// 每层状态治疗系数
        /// </summary>
        public int statusHealPower = 0 ;

        /// <summary> 
        /// 护盾系数
        /// </summary>
        public int shieldPower = 0 ;

        /// <summary> 
        /// 临时获得被动技能效果ID
        /// </summary>
        public int autoSkillID = 0 ;

        /// <summary> 
        /// 文字战报回合前描述1
        /// </summary>
        public int desc1 = 0 ;

        /// <summary> 
        /// 文字战报回合前描述语言包1
        /// </summary>
        public int descID1 = 0 ;

        /// <summary> 
        /// 文字战报回合前描述2
        /// </summary>
        public int desc2 = 0 ;

        /// <summary> 
        /// 文字战报回合前描述语言包2
        /// </summary>
        public int descID2 = 0 ;

        /// <summary> 
        /// 文字战报回合中描述3
        /// </summary>
        public int desc3 = 0 ;

        /// <summary> 
        /// 文字战报回合中描述语言包3
        /// </summary>
        public int descID3 = 0 ;

        /// <summary> 
        /// 文字战报回合中描述4
        /// </summary>
        public int desc4 = 0 ;

        /// <summary> 
        /// 文字战报回合中描述语言包4
        /// </summary>
        public int descID4 = 0 ;

    }
}