// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class SnsEntranceDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 社区名称
        /// </summary>
        public string name = string.Empty ;

        /// <summary> 
        /// 社区名称语言包
        /// </summary>
        public int nameID = 0 ;

        /// <summary> 
        /// 超链接
        /// </summary>
        public int hyperlink = 0 ;

        /// <summary> 
        /// 排序
        /// </summary>
        public int order = 0 ;

        /// <summary> 
        /// 图标
        /// </summary>
        public string icon = string.Empty ;

    }
}