// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class SquareEmojiOffsetDefine
    {
        /// <summary> 
        /// Key
        /// </summary>
        [PrimaryKey] [AutoIncrement] public string ID  { get; set; }

        /// <summary> 
        /// X偏移值
        /// </summary>
        public float valueX = 0 ;

        /// <summary> 
        /// Y偏移值
        /// </summary>
        public float valueY = 0 ;

    }
}