// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class SquareSpacingDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 朝向
        /// </summary>
        public int towards = 0 ;

        /// <summary> 
        /// 分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 间距间距需计算前+后的距离，最前排离边缘需要有个距离+后排距离+后排前方距离才等于0和1的距离
        /// </summary>
        public float spacing = 0 ;

    }
}