// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class StrongHoldDataDefine
    {
        /// <summary> 
        /// 系统流水
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 奇观建筑类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 建筑坐标X
        /// </summary>
        public float posX = 0 ;

        /// <summary> 
        /// 建筑坐标Y
        /// </summary>
        public float posY = 0 ;

        /// <summary> 
        /// 建筑朝向
        /// </summary>
        public int posTo = 0 ;

        /// <summary> 
        /// 连通省份1
        /// </summary>
        public int province1 = 0 ;

        /// <summary> 
        /// 省份1落脚坐标
        /// </summary>
        public int posX1 = 0 ;

        /// <summary> 
        /// 省份1落脚坐标
        /// </summary>
        public int posY1 = 0 ;

        /// <summary> 
        /// 连通省份2
        /// </summary>
        public int province2 = 0 ;

        /// <summary> 
        /// 省份2落脚坐标
        /// </summary>
        public int posX2 = 0 ;

        /// <summary> 
        /// 省份2落脚坐标
        /// </summary>
        public int posY2 = 0 ;

        /// <summary> 
        /// 怪物组编号
        /// </summary>
        public int monsterPointGroup = 0 ;

    }
}