// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class StrongHoldTypeDefine
    {
        /// <summary> 
        /// 奇观建筑类型
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 奇观建筑名称
        /// </summary>
        public int l_nameId = 0 ;

        /// <summary> 
        /// 描述文字1
        /// </summary>
        public int l_desc = 0 ;

        /// <summary> 
        /// 详细描述文字
        /// </summary>
        public int l_desc2 = 0 ;

        /// <summary> 
        /// 建筑类型分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 建筑等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 解锁纪念碑事件
        /// </summary>
        public int openMileStone = 0 ;

        /// <summary> 
        /// 驻守部队容量上限
        /// </summary>
        public int armyCntLimit = 0 ;

        /// <summary> 
        /// 队伍数量上限
        /// </summary>
        public int marchCntLimit = 0 ;

        /// <summary> 
        /// 效果1
        /// </summary>
        public int buffData1 = 0 ;

        /// <summary> 
        /// 效果2
        /// </summary>
        public int buffData2 = 0 ;

        /// <summary> 
        /// 效果3
        /// </summary>
        public int buffData3 = 0 ;

        /// <summary> 
        /// 模型半径
        /// </summary>
        public float radius = 0 ;

        /// <summary> 
        /// 独占区半径
        /// </summary>
        public float radiusCollide = 0 ;

        /// <summary> 
        /// 领地长宽
        /// </summary>
        public int territorySize = 0 ;

        /// <summary> 
        /// 首次占领邮件
        /// </summary>
        public int firstRewardMail = 0 ;

        /// <summary> 
        /// 首次占领展示奖励
        /// </summary>
        public int firstRewardShow = 0 ;

        /// <summary> 
        /// 初始保护时间（秒）
        /// </summary>
        public int initProtectTime = 0 ;

        /// <summary> 
        /// 常规保护时间（秒）
        /// </summary>
        public int protectTime = 0 ;

        /// <summary> 
        /// 常规争夺中时间
        /// </summary>
        public int battleTime = 0 ;

        /// <summary> 
        /// 争夺延长时间
        /// </summary>
        public int battleTimeAdd = 0 ;

        /// <summary> 
        /// 原始怪物ID
        /// </summary>
        public int initMonster = 0 ;

        /// <summary> 
        /// 守护者怪物ID
        /// </summary>
        public int monsterType = 0 ;

        /// <summary> 
        /// 守护者怪物数量
        /// </summary>
        public int monsterNum = 0 ;

        /// <summary> 
        /// 伤亡比例
        /// </summary>
        public int battleLoss = 0 ;

        /// <summary> 
        /// 占领邮件
        /// </summary>
        public int emailId1 = 0 ;

        /// <summary> 
        /// 被抢邮件
        /// </summary>
        public int emailId2 = 0 ;

        /// <summary> 
        /// 建筑模型
        /// </summary>
        public string modelId = string.Empty ;

        /// <summary> 
        /// 展示预制
        /// </summary>
        public string imgShow = string.Empty ;

        /// <summary> 
        /// UI图标
        /// </summary>
        public string iconImg = string.Empty ;

        /// <summary> 
        /// 保护期光效
        /// </summary>
        public string protectEffect = string.Empty ;

        /// <summary> 
        /// 邮件图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 默认的旗帜图标
        /// </summary>
        public string defaultFlag = string.Empty ;

    }
}