// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class StudyDataDefine
    {
        /// <summary> 
        /// ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 科技ID
        /// </summary>
        public int studyID = 0 ;

        /// <summary> 
        /// 文明ID
        /// </summary>
        public int civilizationID = 0 ;

        /// <summary> 
        /// 名称语言包
        /// </summary>
        public int l_studyNameID = 0 ;

        /// <summary> 
        /// 描述语言包
        /// </summary>
        public int l_desID = 0 ;

        /// <summary> 
        /// 图标
        /// </summary>
        public string icon = string.Empty ;

    }
}