// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class StudyDefine
    {
        /// <summary> 
        /// ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 描述语言包
        /// </summary>
        public int l_des = 0 ;

        /// <summary> 
        /// 科技大类
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 科技子类型
        /// </summary>
        public int studyType = 0 ;

        /// <summary> 
        /// 科技等级
        /// </summary>
        public int studyLv = 0 ;

        /// <summary> 
        /// 需求学院等级
        /// </summary>
        public int campusLv = 0 ;

        /// <summary> 
        /// 需求前置科技1
        /// </summary>
        public int preconditionStudy1 = 0 ;

        /// <summary> 
        /// 前置科技等级1
        /// </summary>
        public int preconditionLv1 = 0 ;

        /// <summary> 
        /// 需求前置科技2
        /// </summary>
        public int preconditionStudy2 = 0 ;

        /// <summary> 
        /// 前置科技等级2
        /// </summary>
        public int preconditionLv2 = 0 ;

        /// <summary> 
        /// 需求前置科技3
        /// </summary>
        public int preconditionStudy3 = 0 ;

        /// <summary> 
        /// 前置科技等级3
        /// </summary>
        public int preconditionLv3 = 0 ;

        /// <summary> 
        /// 需求前置科技4
        /// </summary>
        public int preconditionStudy4 = 0 ;

        /// <summary> 
        /// 前置科技等级4
        /// </summary>
        public int preconditionLv4 = 0 ;

        /// <summary> 
        /// 需求粮食
        /// </summary>
        public int needFood = 0 ;

        /// <summary> 
        /// 需求木材
        /// </summary>
        public int needWood = 0 ;

        /// <summary> 
        /// 需求石料
        /// </summary>
        public int needStone = 0 ;

        /// <summary> 
        /// 需求金币
        /// </summary>
        public int needGold = 0 ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_function = 0 ;

        /// <summary> 
        /// 提升类型
        /// </summary>
        public List<string> buffType = null ;

        /// <summary> 
        /// 提升类型
        /// </summary>
        public List<attrType> buffTypeNew = null ;

        /// <summary> 
        /// 提升参数
        /// </summary>
        public List<int> buffData = null ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_buffDesID = 0 ;

        /// <summary> 
        /// 效果描述解析
        /// </summary>
        public string desData = string.Empty ;

        /// <summary> 
        /// 花费时间
        /// </summary>
        public int costTime = 0 ;

        /// <summary> 
        /// 战力
        /// </summary>
        public int power = 0 ;

        /// <summary> 
        /// 图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 所在列数
        /// </summary>
        public int columns = 0 ;

        /// <summary> 
        /// 科技所在位置编号
        /// </summary>
        public int location = 0 ;

    }
}