// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class SystemOpenDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 主城等级开启
        /// </summary>
        public int openLv = 0 ;

        /// <summary> 
        /// 主线任务开启
        /// </summary>
        public int openTask = 0 ;

        /// <summary> 
        /// 国家成就开启
        /// </summary>
        public int openSuccess = 0 ;

        /// <summary> 
        /// 主城等级未达开启条件提示语
        /// </summary>
        public int l_promptID = 0 ;

    }
}