// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class TaskDailyDefine
    {
        /// <summary> 
        /// 任务ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 任务名称
        /// </summary>
        public int l_nameId = 0 ;

        /// <summary> 
        /// 任务描述
        /// </summary>
        public int l_desc = 0 ;

        /// <summary> 
        /// 任务类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 任务参数1
        /// </summary>
        public int param1 = 0 ;

        /// <summary> 
        /// 任务参数2
        /// </summary>
        public int param2 = 0 ;

        /// <summary> 
        /// 任务目标计数
        /// </summary>
        public int require = 0 ;

        /// <summary> 
        /// 任务奖励
        /// </summary>
        public int reward = 0 ;

        /// <summary> 
        /// 任务在分组中排序
        /// </summary>
        public int order = 0 ;

        /// <summary> 
        /// 可显示最低等级（作废）
        /// </summary>
        public int reqLevMin = 0 ;

        /// <summary> 
        /// 可显示最高等级（作废）
        /// </summary>
        public int reqLevMax = 0 ;

        /// <summary> 
        /// 任务图标
        /// </summary>
        public string iconImg = string.Empty ;

        /// <summary> 
        /// 时代编号
        /// </summary>
        public List<int> age = null ;

        /// <summary> 
        /// 积分数量
        /// </summary>
        public int score = 0 ;

    }
}