// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class TaskDialogDefine
    {
        /// <summary> 
        /// 任务ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 对白分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 分组中序号
        /// </summary>
        public int step = 0 ;

        /// <summary> 
        /// 对白内容
        /// </summary>
        public int text = 0 ;

        /// <summary> 
        /// 该句对话方向
        /// </summary>
        public int leftOrRight = 0 ;

        /// <summary> 
        /// 对话指向NPC模型（作废）
        /// </summary>
        public string npcImg = string.Empty ;

        /// <summary> 
        /// 按文明时代指向的模型索引
        /// </summary>
        public List<string> npcAgeModel = null ;

        /// <summary> 
        /// 客户端语言设置
        /// </summary>
        public List<int> languageSet = null ;

        /// <summary> 
        /// 对白语音
        /// </summary>
        public List<string> soundClient = null ;

        /// <summary> 
        /// 对白语音(作废）
        /// </summary>
        public string heroSound = string.Empty ;

    }
}