// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class TaskActivityRewardDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int age  { get; set; }

        /// <summary> 
        /// 活跃度1
        /// </summary>
        public int activePoints1 = 0 ;

        /// <summary> 
        /// 奖励1
        /// </summary>
        public int reward1 = 0 ;

        /// <summary> 
        /// 活跃度2
        /// </summary>
        public int activePoints2 = 0 ;

        /// <summary> 
        /// 奖励2
        /// </summary>
        public int reward2 = 0 ;

        /// <summary> 
        /// 活跃度3
        /// </summary>
        public int activePoints3 = 0 ;

        /// <summary> 
        /// 奖励3
        /// </summary>
        public int reward3 = 0 ;

        /// <summary> 
        /// 活跃度4
        /// </summary>
        public int activePoints4 = 0 ;

        /// <summary> 
        /// 奖励4
        /// </summary>
        public int reward4 = 0 ;

        /// <summary> 
        /// 活跃度5
        /// </summary>
        public int activePoints5 = 0 ;

        /// <summary> 
        /// 奖励5
        /// </summary>
        public int reward5 = 0 ;

    }
}