// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class TaskChapterDataDefine
    {
        /// <summary> 
        /// 章节序号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 章节标题名称
        /// </summary>
        public int l_titleNameId = 0 ;

        /// <summary> 
        /// 目标简述
        /// </summary>
        public int l_descId1 = 0 ;

        /// <summary> 
        /// 详细描述
        /// </summary>
        public int l_descId2 = 0 ;

        /// <summary> 
        /// 序幕背景图
        /// </summary>
        public string preImg = string.Empty ;

        /// <summary> 
        /// 序幕背景图
        /// </summary>
        public string prebg = string.Empty ;

        /// <summary> 
        /// 序幕文本
        /// </summary>
        public int preText = 0 ;

        /// <summary> 
        /// 序章的音效
        /// </summary>
        public string preSound = string.Empty ;

        /// <summary> 
        /// 开启对白
        /// </summary>
        public List<int> dialogBegin = null ;

        /// <summary> 
        /// 结束对白
        /// </summary>
        public List<int> dialogEnd = null ;

        /// <summary> 
        /// 章节奖励
        /// </summary>
        public int reward = 0 ;

        /// <summary> 
        /// 章节文明模型（作废）
        /// </summary>
        public List<string> imgCivRes = null ;

        /// <summary> 
        /// 章节时代模型
        /// </summary>
        public List<string> imgAgeRes = null ;

    }
}