// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class TaskSideDefine
    {
        /// <summary> 
        /// 任务ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 任务名称
        /// </summary>
        public int l_nameId = 0 ;

        /// <summary> 
        /// 任务描述
        /// </summary>
        public int l_desc = 0 ;

        /// <summary> 
        /// 任务类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 任务参数1
        /// </summary>
        public int param1 = 0 ;

        /// <summary> 
        /// 任务参数2
        /// </summary>
        public int param2 = 0 ;

        /// <summary> 
        /// 任务目标计数
        /// </summary>
        public int require = 0 ;

        /// <summary> 
        /// 任务奖励
        /// </summary>
        public int reward = 0 ;

        /// <summary> 
        /// 显示需求等级
        /// </summary>
        public int showLevelReq = 0 ;

        /// <summary> 
        /// 显示需求建筑类型
        /// </summary>
        public int showBuildingReq = 0 ;

        /// <summary> 
        /// 任务所属分组
        /// </summary>
        public int group1 = 0 ;

        /// <summary> 
        /// 任务在分组中排序
        /// </summary>
        public int order = 0 ;

        /// <summary> 
        /// 任务图标
        /// </summary>
        public string iconImg = string.Empty ;

    }
}