// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class TavernRankDefine
    {
        /// <summary> 
        /// ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 分组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 奖励类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 道具&参数ID
        /// </summary>
        public int typeData = 0 ;

    }
}