// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class TavernProbabilityDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 名称语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 概率
        /// </summary>
        public string probability = string.Empty ;

    }
}