// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class TurntableDrawRangeDefine
    {
        /// <summary> 
        /// itempakid
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 转义ID
        /// </summary>
        public int Escape = 0 ;

    }
}