// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class TurntableRangeDefine
    {
        /// <summary> 
        /// 自增序
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 组
        /// </summary>
        public int group = 0 ;

        /// <summary> 
        /// 物品ID
        /// </summary>
        public int itemid = 0 ;

        /// <summary> 
        /// 数量
        /// </summary>
        public int num = 0 ;

        /// <summary> 
        /// 概率
        /// </summary>
        public string range = string.Empty ;

    }
}