// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class TurntableRangeShowDefine
    {
        /// <summary> 
        /// 自增序
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 活动ID
        /// </summary>
        public int activityId = 0 ;

        /// <summary> 
        /// 物品ID
        /// </summary>
        public int itemId = 0 ;

        /// <summary> 
        /// 数量
        /// </summary>
        public int num = 0 ;

        /// <summary> 
        /// 概率
        /// </summary>
        public int range = 0 ;

        /// <summary> 
        /// 排序
        /// </summary>
        public int order = 0 ;

    }
}