// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class TurntableDrawDefine
    {
        /// <summary> 
        /// 自增序
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 转盘类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 概率ID
        /// </summary>
        public int itempack = 0 ;

        /// <summary> 
        /// 可选用的物品替代抽奖（预留）
        /// </summary>
        public int itemId = 0 ;

        /// <summary> 
        /// 首抽保底概率
        /// </summary>
        public int safety_first = 0 ;

        /// <summary> 
        /// 循环次数
        /// </summary>
        public int fornum = 0 ;

        /// <summary> 
        /// 钻石消耗
        /// </summary>
        public int Cost = 0 ;

        /// <summary> 
        /// 每日首次折扣百分比
        /// </summary>
        public int Cost_firt_discount = 0 ;

    }
}