// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class TurntableDrawProgressDefine
    {
        /// <summary> 
        /// 
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 活动ID
        /// </summary>
        public int activity = 0 ;

        /// <summary> 
        /// 达标次数
        /// </summary>
        public int reach = 0 ;

        /// <summary> 
        /// itempackId
        /// </summary>
        public int itempack = 0 ;

        /// <summary> 
        /// 宝箱模型
        /// </summary>
        public string treasureModel = string.Empty ;

    }
}