// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class VillageRewardDataDefine
    {
        /// <summary> 
        /// 系统编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 奖励类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 奖励参数
        /// </summary>
        public int typeData = 0 ;

        /// <summary> 
        /// 奖励数量
        /// </summary>
        public int typeNum = 0 ;

        /// <summary> 
        /// 需求等级
        /// </summary>
        public int reqLevel = 0 ;

        /// <summary> 
        /// 概率权重
        /// </summary>
        public int chance = 0 ;

        /// <summary> 
        /// 奖励描述
        /// </summary>
        public int l_desc = 0 ;

        /// <summary> 
        /// 表现倍率
        /// </summary>
        public int multiple = 0 ;

        /// <summary> 
        /// 倍率提示
        /// </summary>
        public int l_desc2 = 0 ;

    }
}