// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class VipAttDefine
    {
        /// <summary> 
        /// ID
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 等级组
        /// </summary>
        public int levelGroup = 0 ;

        /// <summary> 
        /// 新
        /// </summary>
        public int newSign = 0 ;

        /// <summary> 
        /// 属性
        /// </summary>
        public string att = string.Empty ;

        /// <summary> 
        /// 客户端使用属性
        /// </summary>
        public attrType attNew = attrType.None ;

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_attID = 0 ;

        /// <summary> 
        /// 参数
        /// </summary>
        public float add = 0 ;

        /// <summary> 
        /// 是否整数，1=是
        /// </summary>
        public int integer = 0 ;

    }
}