// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class VipDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 语言包
        /// </summary>
        public int l_nameID = 0 ;

        /// <summary> 
        /// 等级
        /// </summary>
        public int level = 0 ;

        /// <summary> 
        /// 升至下级点数
        /// </summary>
        public int point = 0 ;

        /// <summary> 
        /// 专属宝箱
        /// </summary>
        public int freeBox = 0 ;

        /// <summary> 
        /// 特别尊享
        /// </summary>
        public int specialBox = 0 ;

        /// <summary> 
        /// 特别尊享宝箱价格
        /// </summary>
        public int price = 0 ;

        /// <summary> 
        /// VIP图标
        /// </summary>
        public string icon = string.Empty ;

        /// <summary> 
        /// 补领邮件ID
        /// </summary>
        public int mailID = 0 ;

        /// <summary> 
        /// 通知邮件ID
        /// </summary>
        public int noticeMail = 0 ;

        /// <summary> 
        /// 特别尊享宝箱邮件
        /// </summary>
        public int specialBoxMail = 0 ;

    }
}