// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class VipDayPointDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 天数
        /// </summary>
        public int day = 0 ;

        /// <summary> 
        /// 点数
        /// </summary>
        public int point = 0 ;

    }
}