// Generated by zhengjie
// DO NOT EDIT!!
using SqlCipher4Unity3D;
using System.Collections.Generic;
using GameFramework;

namespace Data
{
    public class VipStoreDefine
    {
        /// <summary> 
        /// 编号
        /// </summary>
        [PrimaryKey] [AutoIncrement] public int ID  { get; set; }

        /// <summary> 
        /// 等级
        /// </summary>
        public int vipLevel = 0 ;

        /// <summary> 
        /// 物品ID
        /// </summary>
        public int itemID = 0 ;

        /// <summary> 
        /// 购买货币类型
        /// </summary>
        public int type = 0 ;

        /// <summary> 
        /// 价格
        /// </summary>
        public int price = 0 ;

        /// <summary> 
        /// 可购买个数
        /// </summary>
        public int number = 0 ;

        /// <summary> 
        /// 折扣
        /// </summary>
        public int discount = 0 ;

    }
}